### ISSUE TITLE
Making Pull Request used a different user

### ISSUE THREAD

**Issue by Toover** [LonamiWebs/Stringlate#103]
From the Android app, making the pull request effectively had an effect by creating this https://github.com/martykan/forecastie/pull/191#issuecomment-304740376, and by showing a fork in the app, but error messages appeared in the app, the contributor user is not the right one (amo?), and I cannot find back _my_ fork on github.

**Comment by Lonami** [comment]
That's really, really strange. You authenticated Stringlate with **your** account, right? I have no clue on how this can have happened. You somehow got access to his account? I'm as surprised as you are!

**Comment by Lonami** [comment]
Cleaning up some issues, reopen if it still happens.
