### ISSUE TITLE
Add an option to show strings that have a translation which is identical to the original

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#105]

**Comment by Lonami** [comment]
I know that Simple Mobile Tools does this with their applications. Where could this option go? How should it be called (to be concise, preferably), and any idea on how it could be done? Just like "Show translated strings"?

**Comment by OffifialMITX** [comment]
Yes, I'd suggest "Show identical strings" beneath "Show translated strings". Also I think strings that match the Application's name should be ignored.

**Comment by Lonami** [comment]
> Also I think strings that match the Application's name should be ignored.

That's harder to tell :)

**Comment by licaon-kter** [comment]
Many apps have localized names, this should be a developer choice `translatable=false`

**Comment by OffifialMITX** [comment]
Well, I guess you're both right.
