### ISSUE TITLE
[Request/Suggestion] Option to scan for .xml other than strings.xml

### ISSUE THREAD

**Issue by Lionirdeadman** [LonamiWebs/Stringlate#106]
I suggest the ability to search for any string to start translating from. What's your input on this?

This would allow for people who don't speak the strings.xml's language but speak another language (example : strings_es.xml) to translate the app.  

_Sent from my LGE LG-D852 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lonami** [comment]
Those should be recognized already. I don't look for `strings.xml` per se anymore, just any `.xml` with `<resources>` and `<string ...` in it. Are you having issues with this?

**Comment by Lionirdeadman** [comment]
Yeah.. I just messed up, sorry about that.. I feel stupid, I made a mistake in the repository name..

**Comment by Lonami** [comment]
@Lionirdeadman don't feel bad about it. It's all cool :)
