### ISSUE TITLE
Text is lost after pressing Next when completely replacing a previous string

### ISSUE THREAD

**Issue by vit1-irk** [LonamiWebs/Stringlate#113]
Steps to reproduce:

1. Try to translate a string
2. Push "next" button
3. Try to go back
4. See that all of the text you typed before is gone

Workaround behavior to avoid such a thing is to switch focus to original string and back to translated one then press "next". But it takes time and finger effort.

P.S. Using Android 7.1 (Lineage OS)

**Comment by Lonami** [comment]
> Try to go back

Back as in pressing the back button or the "previous" button?

**Comment by vit1-irk** [comment]
Previous button

**Comment by Lonami** [comment]
Can't reproduce the issue. Are you using the latest version?:

![cannot-reproduce](https://user-images.githubusercontent.com/6297805/28865283-a33636d4-776f-11e7-956a-2dc2a412de9e.gif)

**Comment by vit1-irk** [comment]
Yes, I've updated Stringlate recently and the bug still remains.

You have to try typing and navigating more times to reproduce this. I noticed that chances to catch the bug are increasing if translation process goes faster, but it's unpredictable.

**Comment by vit1-irk** [comment]
Yay, managed to capture bug on video!
You can see that the "Next" string is gone at the end.

The steps to reproduce are going now this way:

1. Enter some text
2. Go "Next" button
3. Enter some more text
4. Go "Previous"
5. Replace some text maybe
6. Go "Next"
7. Go "Previous"

So the text entered in step 5 is completely lost

![](https://user-images.githubusercontent.com/3207316/28867605-384af01e-77a9-11e7-8822-76ca8043e0d3.gif)

**Comment by Bjornskjald** [comment]
Can confirm.

**Comment by Lonami** [comment]
Okay I got this it seems to happen when you replace the whole string (i.e. first delete all its contents and then add more), not when you simply remove a portion of it.

**Comment by Lonami** [comment]
The fact it had to be an empty string was key :)

> ```
> getTag() would cache the result, but after setting a string
> to empty content, the cached result wouldn't be invalidated.
>
> This caused some operations to update the contents of a now
> ghost tag, hence losing the changes when updating the cache.
> ```
