### ISSUE TITLE
Missing language for translations

### ISSUE THREAD

**Issue by asereze** [LonamiWebs/Stringlate#129]
I've tried to use Stringlate to translate some projects to Sardinian language (ISO 639-1 code: "sc") but the app gives me an error if I try to add that language to a project, and it's not on the language list. Could you add it to the app, please?

**Comment by Lonami** [comment]
Stringlate currently uses [`Locale.getAvailableLocales()`](https://github.com/LonamiWebs/Stringlate/blob/4fe0b694e40f4c283f9026458b535a22c5dc5d20/src/app/src/main/java/io/github/lonamiwebs/stringlate/classes/LocaleString.java#L71) to verify whether a locale is [valid](https://github.com/LonamiWebs/Stringlate/blob/master/src/app/src/main/java/io/github/lonamiwebs/stringlate/activities/translate/TranslateActivity.java#L518) or not, and it's strange that such language is not returned. Android Studio does show such message as valid, so I wonder what source they use. I wonder if it depends on how Android itself was built, or the system version.

**Comment by gsantner** [comment]
@asereze Do you have the option for Sardinian in the android system language list?

**Comment by asereze** [comment]
@gsantner No, unfortunately. I'm using Lineage OS, but I remember not finding it on stock Android as well, on my old phone.

**Comment by Lonami** [comment]
After some discussion we noticed that Android's `.getAvailableLocales()` shows only *installed* locales. There's another method to list all available ISO codes and we're looking into it :)

**Comment by gsantner** [comment]
Than theres still the problem, that sardinian isn't supported by most android roms. that means, that a dev have to manually support language switching to other languages, e.g. sardinian. I'm doing this in most of my apps, but I don't know many apps supporting that

**Comment by gsantner** [comment]
So, you will always have to choose manually in sardinian supporting apps, until android adds support for it officially

**Comment by Lonami** [comment]
Shoot, that's right. Uhm, we would somehow need to let the developers know how this works when using "unlisted". Maybe we could point them to Stringlate's website with more information about how to add a custom locale switcher, and from there refer to your utility?

**Comment by asereze** [comment]
@Lonami Ah, ok. Thank you very much!

@gsantner Yeah, there are a few, but sometimes I had to ask to add it or there have been some problems, like with F-Droid. Usually I ask to translate apps that I already know have that option. Something like that would be really useful. I would also have asked to help translating Android into Sardinian, if I knew of a way/place to do it.

**Comment by asereze** [comment]
@Lonami @gsantner 
Hi guys,
sorry if I'm writing you here, but it looks like Github doesn't have a chat or something like that to contact you. I wanted to ask you: is there a link to this utility, right now? I would like to point it to Kiwix's developers, since they had a problem with locales for a while, as you can see here:

https://github.com/kiwix/kiwix-android/issues/109

And maybe to those working at F-Droid as well, since they had to remove the possibility to change the language from the settings because of a few problems that some users had.

**Comment by gsantner** [comment]
@asereze Language switcher:
maybe take a look at my gsantner/opoc repository. have a working solution that is in use i  about 10 apps. 
Your problem is switching language at runtime as I understand, where stringlate doesnt have anything todo with.

LanguagePreferenceCompat and ContextUtil is what you should need from opoc.

**Comment by asereze** [comment]
Ok, thank you very much!
