### ISSUE TITLE
Export to issue function

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#13]
Maybe as a copy paste sheet like
```xml
<string name="export_to_issue">I've translated the app <a href="AppLink">AppName</a> to <b>locale</b> via <a href="https://github.com/LonamiWebs/Stringlate">Stringlate</a>!</string>
```
which is generated automatically and will look like

<table border="0"><tr><td>I've translated the app <a href="AppLink">AppName</a> to <b>locale</b> via <a href="https://github.com/LonamiWebs/Stringlate">Stringlate</a>!</td></tr></table>

**Comment by XyLoNaMiyX** [comment]
Export to issue… Could also be done. Thanks for the idea!

**Comment by OffifialMITX** [comment]
Are you done with that?

Am 29. Dezember 2016 12:48:45 MEZ, schrieb Lonami <notifications@github.com>:
>Closed #13 via 219f35498ac0c99a06f59885003fe84edbc06c09.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/13#event-907281145

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
Yes, exporting to issue works. Although I would like to be able to *comment* if you have previously made an issue not to bloat the issues section.

**Comment by OffifialMITX** [comment]
Cool and yesm that would be helpful, can't  you implement this from ForkHub or so?

Am 29. Dezember 2016 14:16:25 MEZ, schrieb Lonami <notifications@github.com>:
>Yes, exporting to issue works. Although I would like to be able to
>*comment* if you have previously made an issue not to bloat the issues
>section.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/13#issuecomment-269628845

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by licaon-kter** [comment]
@OffifialMITX #40

**Comment by XyLoNaMiyX** [comment]
> can't you implement this from ForkHub or so?

Can? Sure. Want or need to? Not really. OAuth works just as fine, and although it could either use OAuth or ForkHub (they're not mutually exclusive), I'm not willing to look into it.

As I said, it works so it should serve for most people's purpose.

**Comment by XyLoNaMiyX** [comment]
> Although I would like to be able to comment if you have previously made an issue not to bloat the issues section.

[`a617d64`](https://github.com/LonamiWebs/Stringlate/commit/a617d6415f4baa373eba56f12f132ac0168102b2). It works on a per repository, per locale basis. Two locales for the same repository will obviously use the different issues, but for updates on an already-made issue for a given locale, a comment will now be posted instead.
