### ISSUE TITLE
Creating a GitHub PullRequest should not use an existing master

### ISSUE THREAD

**Issue by centic9** [LonamiWebs/Stringlate#131]
I have a github project where I already have a fork under my account. There are already some changes on my master branch, but I don't want to push those right now. However stringlate did add the translations to master and created a PR with all the other changes. It should rather create a new branch instead to only send the translations.

**Comment by Lonami** [comment]
That's something I had thought about, but now we have more reasons to do so. How should the workflow be? Attempt to fork or no operation if it exists, then create a new branch (i.e. `stringlate-####` with a random number), and commit there?

**Comment by centic9** [comment]
Using the existing fork would be fine, a new branch with a unique name would allow multiple iterations which usually will happen if the app is actively developed, maybe you can simply number them 1, 2, 3 or add a date-string, so they are easier to distinguish/put in order.

**Comment by Lonami** [comment]
Currently we save no information about what previous requests we have made, and a date seems somewhat lengthy (considering we would need more than the year/month/day alone), so it's just a random number.

**Comment by Olf0** [comment]
Worked well for me with Stringlate v0.11 from F-Droid under AOSP 4.1.2 (API level 16) and my own fork used as repository on Github: Stringlate created a new branch correctly.

It took me a while to find the ability to select a specific branch in my repository, though: Only when selecting the "Update strings.xml" in the "Actions" menu (in the upper right screen corner) I was able to select a branch.

But unfortunately Stringlate did not upload any strings successfully, it just created a copy of the selected branch.

Furthermore, using  "Update strings.xml" again, overwrites local changes, although Stringlate states in its "Pull new strings" dialogue: "... will keep your translations intact ..."!

Can provide logs, if helpful.

**Comment by Lonami** [comment]
Using a random branch https://github.com/LonamiWebs/Stringlate/commit/17526de011f56bf562b3a822f76190093442e79a and having fixed PRs https://github.com/LonamiWebs/Stringlate/commit/fbffe5d4c7f59f5a1c117a543e978dc8cf855772 should be enough. Please reopen, leave a comment or open a new issue if you have further concerns.
