### ISSUE TITLE
Utalize stringlate on CLI to sort translations

### ISSUE THREAD

**Issue by gsantner** [LonamiWebs/Stringlate#140]
The target is to use the CLI module to load a application direcotry (path specified by an argument), search in there for the original strings (string\*.xml, arrays\*.xml, .. should be all available from core functionalities already), and reorder all translations and comments.

This means that strings in translated languages should be in the same order than in the original then. See example below.

<table>
<tr><td></td>
<td>Original (values)<img src="https://user-images.githubusercontent.com/6735650/31075392-8fc5d88a-a775-11e7-8138-038958b095c4.png" /></td></tr>
<tr></tr>
<td>Bad order which needs to be fixed /values-de)<img src="https://user-images.githubusercontent.com/6735650/31075394-8fc68898-a775-11e7-85ee-470bcae6a6af.png" /></td>
<td>Fixed order in translation (values-de) <img src="https://user-images.githubusercontent.com/6735650/31075393-8fc5dcb8-a775-11e7-8175-3186b52a5d38.png" /></td></table>

**Comment by Lonami** [comment]
Cleaning up a bit, this is pretty much the same as #66 so we can just keep the oldest issue around.
