### ISSUE TITLE
Wrong repository names

### ISSUE THREAD

**Issue by Madis0** [LonamiWebs/Stringlate#153]
I'm seeing wrong names (all called "Stringlate") for some manually added repositories. When that happens, the "open project homepage" also points to a wrong place (the Stringlate's project page). 

Case in point: 
- https://github.com/DVDAndroid/XposedInstaller (somehow fixed itself after fetching later) 
- https://github.com/koush/InkwireResources (still broken)

![](https://www.pictshare.net/qd7wiv95wj.jpg)

**Comment by Lonami** [comment]
This is very strange, I just installed the version available on F-Droid and tried adding both repositories, by owner/name pair and with the whole URL. They both worked! :/

**Comment by Lonami** [comment]
I'm cleaning up old issues and I can't seem to reproduce this. Please reopen if you have clear steps on how to trigger this exact bug.
