### ISSUE TITLE
Add project as a FAB

### ISSUE THREAD

**Issue by Madis0** [LonamiWebs/Stringlate#154]
The Add project bottom tab should be a floating action button instead, therefore also removing the need of any tab bar at all.

**Comment by Lonami** [comment]
Both would work. Why should the FAB be preferred over swiping?

**Comment by Madis0** [comment]
Because FABs are used for creating things, [per Material Design guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html) and behaviour of many other apps (consistency!). 
I didn't know it swiped though, [bottom tabs shouldn't swipe at all.](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior)

**Comment by Lonami** [comment]
Fair enough.

**Comment by diegoalvis** [comment]
Solve in #155 BTW use lambdas, don't kill cats 😄

**Comment by Lonami** [comment]
#155 merged. Closing issue.
