### ISSUE TITLE
Move "Add repository" to its own activity

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Stringlate#157]
With the addition of a Floating Action Button thanks to #155, there's no need to have two pages in the main screen anymore. The new desired design would hence be:
* Main screen, simply containing the "Project history", with all the added repositories until now. This would of course have the FAB to add new projects.
* When the FAB is clicked, a new activity should appear and contain, on the left side/fragment, the fields needed to enter the project URL and such, and as a second fragment on the right side with the now "discover" activity. Hence, "add project" and "discover" would be merged into one, much like the main screen looks like now.

**Comment by gsantner** [comment]
# nohacktoberfest 😞

**Comment by Lonami** [comment]
The FAB has been removed since it had a few visual glitches. I personally like the tabbed style, and it's easy to move between the two fragments. I don't think a rewrite is needed.
