### ISSUE TITLE
Cannot add new languages

### ISSUE THREAD

**Issue by airon90** [LonamiWebs/Stringlate#158]
I'd like to add a new language for an app but when I select the language (it) the app restarts itself and nothing changed

**Comment by Lonami** [comment]
Version? What application are you trying to translate?

**Comment by airon90** [comment]
I'm using the latest F-Droid version of Stringlate (0.11) and I was trying to translate some apps e.g. [Editor](https://github.com/billthefarmer/editor)

**Comment by gsantner** [comment]
@Lonami maybe  <https://github.com/billthefarmer/editor/blob/master/src/main/res/values/strings.xml#L26> erroring?

**Comment by airon90** [comment]
I don't know if it would help you but even with [Vanilla Tag Editor](https://github.com/vanilla-music/vanilla-music-tag-editor) and [Vanilla Lyrics](https://github.com/vanilla-music/vanilla-music-lyrics-search) Stringlate crashes

**Comment by Lonami** [comment]
Sorry for delay, this week's a bit busy. I have tried to add the `it` locale on all three applications with the F-Droid version and it works on my end. It would be nice if you could get a traceback so we can see where it crashes, or if someone else is willing to try.

**Comment by airon90** [comment]
Tell me how to get a traceback and I will do :)

**Comment by Lonami** [comment]
You can try to connect your device to your computer through USB and run [ADB](https://developer.android.com/studio/command-line/adb.html) (download from [here](https://developer.android.com/studio/releases/platform-tools.html)) like so from a terminal/console:
```
adb logcat -s io.github.lonamiwebs.stringlate
```

Otherwise, and what I would do is build the application myself and run it from Android Studio, although I don't know if you have done this before or know how.

**Comment by airon90** [comment]
My phone broke badly so I bought a new one and there are no problems right now. Unfortunately I close this bug

**Comment by Lonami** [comment]
Sorry to hear! Just to gather a bit more information, what Android version did you have and which one do you have now?

**Comment by airon90** [comment]
5.1.1 now 7.1.2
Anyway, Stringlate worked on my old phone, then I didn't use it because I didn't have spare time. Now I used it and didn't work.

**Comment by Lonami** [comment]
Alright, thanks. I hope this new phone lasts a long time :)
