### ISSUE TITLE
Add about section

### ISSUE THREAD

**Issue by airon90** [LonamiWebs/Stringlate#159]
I suggest to add an About section where to add links to GitHub (repo, bug report), license, authors, ...

**Comment by gsantner** [comment]
@Lonami you can take AboutActivity from OPOC

**Comment by MaxValue** [comment]
+1ing this, because I was searching high and low for a "Report a bug" link inside the app.

**Comment by gsantner** [comment]
gonna be included in next version, stuff is there but not integrated yet

**Comment by gsantner** [comment]
![screenshot-2018-05-18__23-03-07](https://user-images.githubusercontent.com/6735650/40258116-ca4341e4-5af0-11e8-8a2e-334ac9824b65.png)

till an stringlate update is out, take a look at [markor](https://github.com/gsantner/markor)

**Comment by Lonami** [comment]
Nice stuff ♥

**Comment by gsantner** [comment]
;)

can you come to channel ?

**Comment by Lonami** [comment]
What channel? Matrix? Not right now.
