### ISSUE TITLE
strings.xml updater doesn't fully work

### ISSUE THREAD

**Issue by Madis0** [LonamiWebs/Stringlate#163]
Today I wanted to update the translations of an app I had translated in the past. So I opened it in Stringlate and chose "Update strings.xml" from the menu.

 It started loading and updated my GitHub fork, but the percentage stayed the same. Only way I could update the percentage was when I recloned the project.

**Comment by Lonami** [comment]
Sorry for the delay. I'm closing this since it's a somewhat old issue and doesn't have enough information (it only happened once, and we don't know which repository caused this). If the repository was big, it might be that, or perhaps it was a slow network or temporary issue.
