### ISSUE TITLE
Resource filenames wrongly named when exporting via GH Issue

### ISSUE THREAD

**Issue by gsantner** [LonamiWebs/Stringlate#166]
Filenames are just noted via commented, `strings`+number+`.xml`. They should be named (as comment) like the original filenames.

See issue <https://github.com/Diaspora-for-Android/dandelion/issues/177> and related data at this point <https://github.com/Diaspora-for-Android/dandelion/tree/v1.0.8/app/src/main/res>

**Comment by gsantner** [comment]
Noticed, that the last file is too missing `<?xml version="1.0" encoding="utf-8"?>`

**Comment by Lonami** [comment]
> like the original filenames

The original filenames for translations are *not* preserved. The translations are merged into a single file, internally `strings.xml`, so it's easier to work with, while the default translation preserves all the files that were in the orignal project, as well as their names, so exporting can still be done correctly (and each string be put into the right file). Preserving also the translated filenames would require a few changes :/

**Comment by gsantner** [comment]
just as a note, we could also preserve data directly in each translateable document loaded, but not exporting it. e.g. using some invalid char as prefix
