### ISSUE TITLE
The new, big "+" button introduced in Stringlate 0.12 obstructs too much space in landscape orientation

### ISSUE THREAD

**Issue by Olf0** [LonamiWebs/Stringlate#170]
The new, big, orange "+" button introduced in Stringlate 0.12 obstructs too much space in landscape orientation, hence the list of subscribed repositories is barely visible (only a fraction of the topmost entry).
IMO, the small, black "+" button in Stringlate 0.11 was fine, thus I am suggesting to revert this change.
Furthermore the old, small, black "+" button still exists in Stringlate 0.12, hence the big, orange one just duplicates this functionality.

Screenshots to illustrate this issue:
* Stringlate 0.12 in landscape orientation 
![stringlate0.12.png](https://user-images.githubusercontent.com/16547876/33531033-25b11ce0-d888-11e7-8686-cdcbcc3e9faf.png)
* Stringlate 0.11 in landscape orientation 
![stringlate0.11.png](https://user-images.githubusercontent.com/16547876/33531215-1e94da94-d88a-11e7-84de-e063adfd25bc.png)

**Comment by Madis0** [comment]
I agree that it is a duplicate, so I suggest removing the bottom bar as it has no use as of now.

**Comment by Madis0** [comment]
#157

**Comment by Olf0** [comment]
The big, orange "+" button would need the following enhancements to be able to substitute the bottom bar (i.e. its "History" and "Add" buttons) in functionality:
1. The list of subscribed repositories must be altered, as the "+" button always obstructs the end of the "% translated" bar: In portrait orientation the last visible entries of the list, in landscape orientation all entries.
2. The empty (overdrawn) space before and above (not "behind and above") the "+" button must be eliminated.
3. The behaviour of the "back" button in the "new repository" subwindow must be altered: Currently Stringlate is closed then, but there is no other way to just close this window (i.e. a "cancel" action), except for the "History" button in the bottom bar.

Even with these bug fixes, the new, big, orange "+" button still eats (otherwise available) screen space and provides no new function, compared to "History" and "Add" buttons in the bottom bar.
Furthermore, the bottom bar is extensible with more buttons, when needed.

Thus the by far easiest approach is to revert the addition of the big, orange "+" button.

**Comment by gsantner** [comment]
..or some "overscroll" padding, e.g. 68 dp

**Comment by Madis0** [comment]
Well, it does give more screen space when there is no static bottom bar, just one covered corner. Besides, tabs can be (and should be, IMO) on top too, with toolbar autohide when screen space is needed.

**Comment by Lonami** [comment]
The button is completely useless indeed. I've removed it on https://github.com/LonamiWebs/Stringlate/commit/0f8d40ebd323d41793db20e581c83c948357956d (sorry for the delay, been busy). One can achieve the same effect by either sliding or tapping the desired tab.
