### ISSUE TITLE
"Cancel"-button when downloading a repository

### ISSUE THREAD

**Issue by MaxValue** [LonamiWebs/Stringlate#171]
When initially downloading a repo, you see the loading bar, the percentage, the name and some more information. But there is no way to cancel the download. One may want to do that when they realize that the internet connection sucks at the moment and they want to download it sometime later.

**Comment by Lonami** [comment]
Sorry for the delay :) been busy.

**Comment by MaxValue** [comment]
That sounds like the user cannot cancel while the actual download is happening. Can the user cancel while the download is running? (Without force-closing the app)

**Comment by Lonami** [comment]
You tap the repository *while* the download is happening. Tapping an already-downloaded repository does nothing (long press those for more options).
