### ISSUE TITLE
Add zh-cn, zh-tw, zh-hk and remove zh

### ISSUE THREAD

**Issue by billchenchina** [LonamiWebs/Stringlate#173]

**Comment by gsantner** [comment]
Sorry? Description?

**Comment by billchenchina** [comment]
"zh" can mean "zh-cn", "zh-tw" and "zh-hk"(and so on).And only "zh" probably cause trouble to translators.

So my advice is to remove "zh" and add "zh-cn" instead.

**Comment by gsantner** [comment]
Stringlate just generates a list of all locales available on the device, it is not handmade. We have to think what and if to make modification on this.

cc @Lonami

**Comment by billchenchina** [comment]
Well... Perhaps it's ok to have `values-zh-rCN` and `values-zh-rSG`.

Thanks.

**Comment by gsantner** [comment]
Android support seems to be limited here. <https://stackoverflow.com/a/4249345>

**Comment by billchenchina** [comment]
Get it.Closed
