### ISSUE TITLE
Search result doesn't like translated strings

### ISSUE THREAD

**Issue by Madis0** [LonamiWebs/Stringlate#177]
When searching for a phrase, it accepts both the original and translated phrase and shows results accordingly. When clicking a search result though, it works only if I searched in original language. 

https://streamable.com/xbhwv

**Comment by Lonami** [comment]
I see the issue now. When searching for a string we filter on either the original or the translated content. But, when displaying the string on the translate activity, we only filter the default resources (original language) and then use that to know which translated strings to show.

**Comment by Lonami** [comment]
Sorry for the delay, thanks for the report. Been busy with a few other things :)
