### ISSUE TITLE
Stringlate escapes special characters

### ISSUE THREAD

**Issue by nikoss** [LonamiWebs/Stringlate#182]
@billthefarmer said:
> You don't need to escape quotes in strings in XML, it causes errors.

As if I know how to do that... :)

What happened was that this string...
```
  <string name="version" formatted="false">Editor version %s\nBuilt
  %s\nCopyright \u00A9 2017 Bill Farmer\nFrench translation by <a
  href="https://github.com/milouse">Étienne Deparis</a>\nGerman
  translation by <a href="https://github.com/Markus00000">Markus
  Weimar</a>\nItalian translation by <a
  href="https://github.com/airon90">Michael Moroni</a>\nPolish
  translation by <a href="https://github.com/evo16">Evo</a>\nLicence
  <a href="https://www.gnu.org/licenses/gpl.txt">GNU GPLv3</a>
</string>
```
... , 
(after I added the translation, and exprorted-copied the produced file) 
was printed as the following, by Stringlate:
```
  <string name="version" formatted="false">Έκδοση του Επεξεργαστή %s\n
  Σύνθεση  %s\n
  Πνευματικά δικαιώματα \\u00A9 2017 Bill Farmer\n
  Γαλλική μετάφραση από <a href=\"https://github.com/milouse\" >Étienne Deparis</a>\n
  Γερμανική μετάφραση από <a href=\"https://github.com/Markus00000\" >Markus   Weimar</a>\n
  Ιταλική μετάφραση από <a href=\"https://github.com/airon90\" >Michael Moroni</a>\n
  Πωλονική μετάφραση από <a href=\"https://github.com/evo16\" >Evo</a>\n
Άδεια <a href=\"https://www.gnu.org/licenses/gpl.txt\" >GNU GPLv3</a></string>
```

Also, in another project, the string...
`<string name="thank_you">Thank You</string>`
was exported as...
`<string name="thank_you">Σ\' Ευχαριστώ</string>`

So, `"` is exported as `\"`
and `'` is exported as `\'` .

**Comment by billthefarmer** [comment]
I had not realised this was down to Stringlate. There is another issue with this particular translation in that there is a newline in the translated string after each \n newline character. It looks nice and tidy in the translation, but it causes the lines not to line up in the dialog. This is why there is no blank space after each \n in the original string. I apologise if this is not a Stringlate issue.

**Comment by Lonami** [comment]
I would swear the quotes need to be escaped. That's a check I intentionally added (if I recall correctly), not something that happens by default so it's easy to remove after w edouble check. Regarding `\u00A9` turning into `\\u00A9` we might have an issue there (we need to detect whether it's a escape sequence or if the user did intend to put `\` and then `u00A9`, users shouldn't worry about escaping `\\`).

About the newlines I had no idea that could happen :P do you know of a better tidy way to keep the newline so it's more appealing yet not breaking other things?

**Comment by Lonami** [comment]
Maybe we can check if the following character is an ASCII letter, and if it is, we *don't* escape `\`?

**Comment by billthefarmer** [comment]
This is the [pull request](https://github.com/billthefarmer/editor/pull/43) for this particular translation. There are two commits, one of them has a red x against it. If you click on it, you get the Travis CI build page for that commit, which failed. The reason for the failure, if you scroll down, is:
> /home/travis/build/billthefarmer/editor/src/main/res/values-el/strings.xml:33:33: Error: Open quote is expected for attribute "href" associated with an  element type  "a".

**Comment by Lonami** [comment]
I forgot strings can contain HTML tags, oopsie. That's gonna make this somewhat tricky…

**Comment by Lonami** [comment]
Or not (I was looking at the opposite unparse method). Maybe counting how many `<` and `>` we're inside of is enough, and if the count is not zero we just don't escape quotes.

**Comment by billthefarmer** [comment]
I haven't got around to looking at your app, but you only present strings from XML files for translation, as I understand it, so I don't understand why you need to do anything to the translated text other than put it back into a XML file. HTML is a subset or particular implementation of XML, it wasn't when it was dreamed up, but it is now. Therefore the same rules apply.

Also you are taking strings out of a working published app for translation. If there was anything wrong with the strings the developer would have fixed it as you can't build an app with broken strings. Therefore you shouldn't be doing anything with them.

**Comment by Lonami** [comment]
> Therefore you shouldn't be doing anything with them.

Disagree. Users shouldn't need to know about special sequences like `&lt;` or that quotes need to be escaped (what does even escaping mean they might ask?), so if we can ease this then there's that. I definitely can just keep everything as is though.

**Comment by gsantner** [comment]
just an idea: Why not use CDATA when a escape-must char is detected? this way the user and we dont have to care

**Comment by billthefarmer** [comment]
Well my whole point is that quotes don't need to be escaped, nor do < and > need to be encoded to `&lt;` and `&gt;`. When I get a pull request for a translation for one of my apps I can't tell that Stringlate has been used unless it is mentioned. I just notice that some of the strings need some TLC for the app to build correctly.

**Comment by gsantner** [comment]
@billthefarmer Please reread your comment or at least try what you suggest to be wrong :).

You must special handle <>, be it using CDATA or sequence `&lt;`. `<string name="move">Mov<ae</string>` for example is not a valid translation.
![grafik](https://user-images.githubusercontent.com/6735650/36995575-bccede5e-20b4-11e8-9046-62b96306d00b.png)

Same for apostrophes (not quote): 
![grafik](https://user-images.githubusercontent.com/6735650/36995735-25f65754-20b5-11e8-8de9-411166b9183d.png)


> When I get a pull request for a translation for one of my apps I can't tell that Stringlate has been used unless it is mentioned. 

Stringlate PR's should all include a message for that - see for example <https://github.com/gsantner/memetastic/pull/80>

**Comment by nikoss** [comment]
@Lonami 
> Users shouldn't need to know about special sequences like...

As a user, I can say that one of the first things you learn, when translating,
is that you don't alter special characters.
That applies, at least, to gettext (.pot, .po, .mo files, usually for Gtk programs)
and to Qt based programs.
So we don't alter stuff like %s, %d, html tags, links, etc.

I think @billthefarmer is right on this one.

And now that you mention it,
I remember in another occasion, some characters like `&olt;`
appearing in a file exported by Stringalte.
I didn't gave it much thought then and just deleted the "weird" part.
Maybe it was meant to be something like `»`
(Greek quotes symbol).

If some special characters need some special treatment,
they must have already been altered by the developer of the app.

You might want to take a look on how Poedit and Lokalize work.

**Comment by Lonami** [comment]
This should cover most cases without giving up on the convenience we already had.

**Comment by gsantner** [comment]
@Lonami :tada:
