### ISSUE TITLE
Fail on create a fork

### ISSUE THREAD

**Issue by jeisoncp** [LonamiWebs/Stringlate#186]
I'm traying to update pt-BR translation by pull request, but Stringlate only gives me "Fail on fork".

I already reset my GitHub authorization, anyway the error stills on.

**Comment by treyssatvincent** [comment]
Same bug here, @jeisoncp do you have 2FA enabled on your github account ?

**Comment by gsantner** [comment]
Have 2fa currently temporary disabled and no it's not related to that. @Lonami did the github-apikey maybe get invalid?

**Comment by Lonami** [comment]
```
I/System.out: calling to https://api.github.com/repos/LonamiAlt/stringlate-test/pulls?access_token=----
              ...with params {"title":"Updated es (Spanish) translation","head":"Lonami:stringlate-es-5233","base":"stringlate-es-5233","body":"Commit made via [Stringlate](https:\/\/lonamiwebs.github.io\/stringlate\/)"}
I/System.out: read from network: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"base","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
I/System.out: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"base","code":"invalid"}],"documentation_url":"https:\/\/developer.github.com\/v3\/pulls\/#create-a-pull-request"}
W/System.err: org.json.JSONException: No value for html_url
```

Prettified response:
```json
{
    "message": "Validation Failed",
    "errors": [
        {
            "resource": "PullRequest",
            "field": "base",
            "code": "invalid"
        }
    ],
    "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}
```

It doesn't give too much information.

**Comment by Lonami** [comment]
![image](https://user-images.githubusercontent.com/6297805/38419197-c34f1e0c-399f-11e8-83df-452612255ca2.png)

**Comment by Lonami** [comment]
Nevermind the error message *is* helpful. It's telling you the field `"base"` is invalid. Indeed, `"base"` has to be an *existing branch* on the target repository. Chances are the random branches Stringlate creates on the fork don't exist in the target repository.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Stringlate/commit/460f27ee37ac1e784de08e6028001f5ac4883dd5 should fix `FileNotFoundError` crash related to this.

**Comment by Lonami** [comment]
We should revert https://github.com/LonamiWebs/Stringlate/commit/17526de011f56bf562b3a822f76190093442e79a with some modifications to support selecting the *base* branch (on to which it will be merged) while keeping a sensible default.

**Comment by Lonami** [comment]
We really need more helpful messages there.
