### ISSUE TITLE
export as "pull request"

### ISSUE THREAD

**Issue by mdtrooper** [LonamiWebs/Stringlate#19]
Hi.

Your app is awesome, thanks.

But I wonder when will be the support for the "pull request"?

Regards.

**Comment by XyLoNaMiyX** [comment]
Probably for version `1.0`. I also need to implement a way to log in to GitHub, and to keep the user credentials secure. Need to look into that, but it will be done.

Thanks for your interest!

**Comment by XyLoNaMiyX** [comment]
That was a big challenge :)

Would you like to test out @licaon-kter? ;) You can use [this](https://github.com/LonamiWebs/Strest) or [this](https://github.com/XyLoNaMiyX/Dummy) repository before I delete them.
