### ISSUE TITLE
stringlate adding unnecessary escape characters

### ISSUE THREAD

**Issue by connyduck** [LonamiWebs/Stringlate#190]
#### General information

* **App version:** 0.13
* **System:** 

see here for an example https://github.com/tuskyapp/Tusky/pull/574

**Comment by Lonami** [comment]
Sorry about that! This was supposed to be fixed on https://github.com/LonamiWebs/Stringlate/commit/14557f51e071d77796fcb8cb764d434f8ea26419 but I put the flag switch in the wrong branch of the conditional (and I haven't pushed that fix yet).
