### ISSUE TITLE
Stringlate crashes after "DISCOVER PROJECTS --> Synchronizing"

### ISSUE THREAD

**Issue by Olf0** [LonamiWebs/Stringlate#191]
#### Steps to reproduce:
1. Start Stringlate.
2. Tap on "**+** Add project".
3. Tap on "**/**  DISCOVER PROJECTS".
4. Tap on "🔃".
5. Wait until the download of data finishes.
6. Stringlate crashes.

**Logs** (filtered for *lonamiwebs*): [Main log](https://github.com/LonamiWebs/Stringlate/files/1911318/alogcat.2018-04-15-00-02-04.0200.txt) and [Event log](https://github.com/LonamiWebs/Stringlate/files/1911319/alogcat.2018-04-15-00-02-19.0200.txt)

Tested with Stringlate 0.13 from F-Droid under AOSP 4.1.2 (API level 16).

**Comment by gsantner** [comment]
What is your locale / which language do you use? This may be due to an error in translation.

**Comment by Olf0** [comment]
In *Settings --> Appearance* the default language is selected: *System » English (English, United Kingdom)*

At the command line, looking at the environment variables: `LANG=C`, `LC_ALL=C` and `SYSTEM_USER_LANG=en.GB.utf8` (no `LOCALE` set)

IMO Stringlate should download repository data regardless of these system-wide and Stringlate-internal language settings.

**Comment by gsantner** [comment]
The thing is that strings contain text tokens. If a translator fails to insert or update them the app can't insert on a/any position and crashes. that happened at discover at least once hence asking.

**Comment by Lonami** [comment]
From the log this seems to be the faulty line?:
https://github.com/LonamiWebs/Stringlate/blob/c78cead0ab1e9c1c04ce4ae508739a6df6048350/src/app/src/main/java/io/github/lonamiwebs/stringlate/classes/applications/ApplicationListParser.java#L89

It also mentions this line:
https://github.com/LonamiWebs/Stringlate/blob/c78cead0ab1e9c1c04ce4ae508739a6df6048350/src/app/src/main/java/io/github/lonamiwebs/stringlate/classes/applications/ApplicationListParser.java#L195-L200

[Documentation](https://developer.android.com/reference/org/xmlpull/v1/XmlPullParser.html#next()) sadly doesn't say when this can throw an exception… Only which.

Sadly I can't reproduce the issue. Perhaps F-Droid returned a faulty file based on your location (not sure how they work)? Stringlate just reads https://f-droid.org/repo/index.jar. Can you try downloading it from your phone and posting it somewhere so I can try reading it locally? That's all I can think of.

**Comment by Olf0** [comment]
> Can you try downloading it from your phone and posting it somewhere so I can try reading it locally?

Sure, `curl -O https://f-droid.org/repo/index.jar` downloaded [index.jar](https://github.com/Olf0/MyPlayground/raw/master/index.jar) on my phone a few minutes ago (2016-04-16).
(As you don't seem to trust F-Droid, `md5sum /data/app/io.github.lonamiwebs.stringlate*.apk` outputs
`9fe6e699390a03264bd595aa3cc11035  /data/app/io.github.lonamiwebs.stringlate-1.apk`, which is the Stringlate 0.13 APK installed via the F-Droid client app).

**Comment by Olf0** [comment]
BTW, deleting Stringlate's cache and / or appdata (which ought to reset it to a state as if freshly installed, AFAIU) did not make any difference either, unfortunately.

**Comment by gsantner** [comment]
> As you don't seem to fully trust F-Droid

This has not todo with F-Droid. There are two things now.

1) A problem with xml parser of android. that was fixed at Android 5 or something. thats why you cant parse some stuff. (as in very little amount)

2) Real F-Droid problem, which happened today, like 5 hours ago. But this is not related to your stuff. F-Droid index is currently broken as you can see in forums (and by doing F-Droid pull-down-refresh). Maybe when you read this it is fixed. 

But anyway, you should be able to find a stringlate update when F-Droid repo works again, and the update will fix your problem.

**Comment by Olf0** [comment]
@gsantner, thanks a lot for your comment (a little highlight on this grim day : ) )

> A problem with xml parser of android. that was fixed at Android 5 or something. thats why you cant parse some stuff. (as in very little amount)

That is interesting and may explain other issues with recent APKs, I experience.
Do you have a pointer (e.g. URL) to a specific description of this issue at hand?

> Real F-Droid problem, which happened today, like 5 hours ago. [...] F-Droid index is currently broken as you can see in forums (and by doing F-Droid pull-down-refresh). [...]

I just realised that synchronising the F-Droid repository metadata always emits `Error during update: tmp_f-droid_apk.version may not be NULL (code 19)` in the F-Droid client, so thanks for saving me the time to further investigate this.

> But anyway, you should be able to find a stringlate update when F-Droid repo works again, and the update will fix your problem.

Kudos, will try out tomorrow. :)

**Comment by gsantner** [comment]
code fix https://android.googlesource.com/platform/libcore/+/3f1a5eb%5E!/

info https://stackoverflow.com/questions/37499842/java-lang-illegalargumentexception-illegal-character-d83d

**Comment by Lonami** [comment]
> Real F-Droid problem

Today some friends woke me up with [these](https://gitlab.com/fdroid/fdroidclient/issues/1418) news which apparently talk about the index too and how it was "broken".

And looking by myself, the first post in the [first](https://forum.f-droid.org/t/exception-when-updating-repositories/2594) [three](https://forum.f-droid.org/t/f-droid-fails-to-update-itself/2588) [posts](https://forum.f-droid.org/t/error-opening-index-jar-file-of-personal-repo/2569) as of now also talks about this exception ^^. Anyway glad the issue is fixed.

**Comment by Olf0** [comment]
Yeah, both (*this* issue and the broken F-Droid index) are working fine now.

And the functionality is really nice, now that I have seen it (I already wondered what F-Droid has to do with translating strings at GitHub).  Merci.
