### ISSUE TITLE
Stringlate fails to construct a valid repository URL

### ISSUE THREAD

**Issue by Olf0** [LonamiWebs/Stringlate#192]
#### Steps to reproduce:
1.  Start Stringlate.
2.  Tap on "+ Add project".
Example repository URL is *https://github.com/owner/repository*, see: ![screenshot_20180415_001](https://user-images.githubusercontent.com/16547876/38773364-930dcf8e-404a-11e8-845d-f60aecf63330.png)
3. Enter something in the field "GITHUB *owner*": The URL is altered to _https:_***\/***_github.com/\<something\>/_, see: ![screenshot_20180415_003](https://user-images.githubusercontent.com/16547876/38773383-096fc204-404b-11e8-8761-c230e23fb549.png)
4. Enter something in the field "GITHUB *repository*": The URL is altered to _https:_***/***_github.com/\<something\>/\<other something\>_***.git***, see: ![screenshot_20180415_002](https://user-images.githubusercontent.com/16547876/38773388-6d3af1fa-404b-11e8-9553-6dd5ed98eb4a.png)

#### Expected behaviour:
1. Stringlate to retain the double slash in the URL from the example URL, when the field "GITHUB *owner*" is filled.
2. Stringlate to be consistent, if a repository URL should be terminated with ***.git***.
    * If so, show it in the example URL: *https://github.com/owner/repository.git* (instead of  *https://github.com/owner/repository* currently).
    * If not, do not automatically append *.git* to the content of the field "GITHUB *repository*".

#### General information:
Tested with Stringlate 0.13 from F-Droid under AOSP 4.1.2 (API level 16).

#### Side note:
Currently I fail to successfully retrieve any repository for translating, but that is another issue.

**Comment by Lonami** [comment]
Thanks, this was fixed on https://github.com/LonamiWebs/Stringlate/commit/f3947f07f1494f572a075154b54e9fb3e3891a3c. We really need to push a new version soon!

**Comment by Olf0** [comment]
AFAICS, commit [f3947f0](https://github.com/LonamiWebs/Stringlate/commit/f3947f07f1494f572a075154b54e9fb3e3891a3c) addresses only "Expected behaviour: 1.".

Point 2 of "Expected behaviour" (i.e. inconsistent use of *.git* postfix) seems to be still open.

**Comment by Lonami** [comment]
The `.git` suffix behaviour is somewhat inconsistent indeed. I think we can remove it all together, since GitHub will accept a `git clone` with either the suffix or not.

**Comment by Olf0** [comment]
@Lonami, thanks.

> Thank you for putting so much effort in your issues, [...]

* When I had Stringlate mostly working, it was so useful finding translation issues (primarily by displaying source and target strings next to each other), even though I have not yet managed to export anything (to SD-card or uploading to GitHub).
* Stringlate is IMO an important piece of software infrastructure for Android, enabling internationalasation for projects not relying on Transifex, Pootle etc.
* Although I hope hitting issues related to ancient Android versions comes to an end, there may be other users of SailfishOS or BlackberryOS 10.3 with their Android 4 based runtime environments (API 16 under SFOS on Jolla 1 phones, API 18 under bbOS 10.3, API 19  under all other SFOS devices; all three still actively maintained (sans AOSP updates) and the latter continually being sold) benefiting from these fixes.

**Comment by Olf0** [comment]
v0.14 is working fine (besides commit [5a4eb38](https://github.com/LonamiWebs/Stringlate/commit/5a4eb38729d18175004093eed7bfb967aa39ff9a), which apparently came in later).
