### ISSUE TITLE
Needs a logo

### ISSUE THREAD

**Issue by tebriz159** [LonamiWebs/Stringlate#198]
Hello. I liked your idea this project is good enough to reach the succes. And   I think it's time to make a lpgo for this project. If you want please just comment below.

**Comment by licaon-kter** [comment]
Is this some self-assigned utopian.io task that you did in the hopes of winning some crypto-currency?

**Comment by gsantner** [comment]
@licaon-kter I too get many such very small reports having something utopian in text. Can you tell me something about it?

**Comment by licaon-kter** [comment]
@gsantner not really, my post above should explain it all (as far as I undorstood it)
