### ISSUE TITLE
Add ability to translate from locale A (rather than default) to locale B

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Stringlate#20]
If a person can talk both *French* and *Spanish*, and the *Spanish* locale is already available, it's logical that they should be able to use *Spanish* as **reference**, rather than the **default** (usually *English*).

**Comment by OffifialMITX** [comment]
Works only if the other locale is translated perfectly.

**Comment by XyLoNaMiyX** [comment]
Yes, maybe it would be a bit like the *Chinese Whispers* game. But on the other hand, I think it's good to give a chance to those people who can't talk the language used by default.

**Comment by rr-vesp** [comment]
I agree with that. Sometimes I don't exactly understand the string. However if I could compare it with French or Spanish translations than I should get the right meaning.

**Comment by XyLoNaMiyX** [comment]
> However if I could compare it with French or Spanish translations than I should get the right meaning.

But what if those translations also are under the wrong context too @rr-vesp, and the mistake grows?

**Comment by k3b** [comment]
Currently the translation gui has a field "original string" that shows the translation source.

If this would change to somethink like 

* "current english translation" : ......
* "current spanish translation" : ......
* "current german translation" :  ......

and in the options menu the translater can choose which additional existing translations he/she would like to see.

**Comment by Lonami** [comment]
Should be closed since [`v0.10`](https://github.com/LonamiWebs/Stringlate/releases/tag/v0.10) with the addition of "peek translations". Thanks everyone!
