### ISSUE TITLE
Stringlate fails to add or synchronise repositories hosted at Github

### ISSUE THREAD

**Issue by Olf0** [LonamiWebs/Stringlate#200]
#### Steps to reproduce
1. Start Stringlate.
2. Tap on "**+**  Add project".
3. Enter a valid repository URL on Gihub.
4. Tap on "**▶**  START TRANSLATING".

or

1. Start Stringlate.
2. Tap on "**+**  Add project".
3. Tap on "**/** DISCOVER PROJECTS".
4. Select a project, which is hosted on Github (may need to hit "🔃" first).
5. Tap on "**▶**  START TRANSLATING".

or

1. Start Stringlate.
2. Tap on a subscribed repository.
3. Tap on the menu button ("︙") in the upper right corner.
4. Tap on the menu entry "🔃 Update strings.xml".

In all cases I experience a "Failed to synchronize \<project\>.", tried https://github.com/JusticeRage/ApkTrack and a couple of other repositories at Github:

 ![screenshot_20180421_006](https://user-images.githubusercontent.com/16547876/39079158-8fbb6f06-4515-11e8-91f0-4f9b004f7b28.png)

In contrast to that adding and synchronising repositories on Git*lab* are working, e.g. https://gitlab.com/x653/bullseye and https://gitlab.com/krt/ffupdater!

#### Expected behaviour
A new repository is added or `strings.xml` is updated.

#### Observations
* I stumbled across this issue, when trying to add [ApkTrack](https://github.com/JusticeRage/ApkTrack) in Stringlate 0.14.  As I once added https://github.com/JusticeRage/ApkTrack successfully in Stringlate 0.10 (or 0.11; I don't remember) and updated `strings.xml` subsequently with v0.11, I went back to these versions, and they both fails to add ApkTrack now!?!  Hence I tried a couple of other repositories and none of those hosted at Github was working with Stringlate (used v0.14 for that).
* I checked, if anything relevant WRT to the internationalisation of ApkTrack changed, but found nothing.

#### General information
Tested with Stringlate 0.14 from F-Droid under AOSP 4.1.2 (API level 16).

#### Log
[Main log](https://github.com/LonamiWebs/Stringlate/files/1934051/alogcat.2018-04-21-03-44-35.0200.txt), filtered for `lonamiwebs`, when trying to add https://github.com/JusticeRage/ApkTrack as a new repository.

**Comment by gsantner** [comment]
Further discussion at #201 as seems like system problem
