### ISSUE TITLE
Detect usage of Crowdin

### ISSUE THREAD

**Issue by NotSoImportant** [LonamiWebs/Stringlate#207]
see https://github.com/federicoiosue/Omni-Notes/pull/483
arrays.xml and strings.xml will contain the comment "-"

**Comment by Lonami** [comment]
Actually…
https://github.com/LonamiWebs/Stringlate/blob/50f05c232353a8187ad29eb3b5a4edae9f05809d/src/core/src/main/java/io/github/lonamiwebs/stringlate/classes/git/GitWrapper.java#L35-L37

https://github.com/LonamiWebs/Stringlate/blob/50f05c232353a8187ad29eb3b5a4edae9f05809d/src/core/src/main/java/io/github/lonamiwebs/stringlate/classes/git/GitWrapper.java#L315-L322

And:
![image](https://user-images.githubusercontent.com/6297805/39348961-7dc85758-49f9-11e8-99c1-f0c93903044a.png)

Maybe what we need is #194? :P

**Comment by NotSoImportant** [comment]
oh yea, thank you ;-)
#194 +1
