### ISSUE TITLE
Bug: Issue with strings.xml that contain \n for newline

### ISSUE THREAD

**Issue by NotSoImportant** [LonamiWebs/Stringlate#208]
Stringlate changes entries that contain the sequence "\n" to separate lines.
Example:
```diff
-    <string name="unableToReadDictionaryDir">Fehler beim Lesen des Wörterbuch Verzeichnis: \n%1$s\n\nAndroid externer Speicher Verzeichnis: \n%2$s</string>
+    <string name="unableToReadDictionaryDir">Fehler beim Lesen des Wörterbuch Verzeichnis: \n
+  %1$s\n
+  \n
+  Android externer Speicher Verzeichnis: \n
+  %2$s</string>
```

**Comment by Lonami** [comment]
This is done for readability purposes (when reading the `.xml` file), and it should have no effect in the final translation.

**Comment by NotSoImportant** [comment]
Actually it was included in my final pull request

**Comment by Lonami** [comment]
Yes, it's done for readability purposes in the `.xml` file, so when you export the result, it's added, so it can be easily read.

**Comment by NotSoImportant** [comment]
see several issues, just mentioned here:
https://github.com/rdoeffinger/Dictionary/pull/89/commits/6cb63df208fff94b489d1bda2321f1dbd74bff44
