### ISSUE TITLE
Keep the original xml structure included comments

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#21]
Just look <a href="https://github.com/SimpleMobileTools/Simple-Gallery/issues/10">here</a>.

**Comment by XyLoNaMiyX** [comment]
Sorry, could you be a bit more precise? I don't know what you want to show me on that link.

Do you mean to save/export the translated resources the same way how the `strings.xml` is formatted for default?

**Comment by OffifialMITX** [comment]
Exactly, the issue is that the strings were resorted alphabetically and the comments deleted what the dev don't like to work with.

**Comment by XyLoNaMiyX** [comment]
Maybe I could make it in such a way that the default resources can **not** be modified, then use that file as a *template* and replace the strings with the translation.

It probably is not that easy though, since chances are that the XML parser ignores empty lines and comments. I find myself writing an own parser-like class…

**Comment by OffifialMITX** [comment]
That's basicly what I've thought of either.

Am 21. Dezember 2016 22:37:12 MEZ, schrieb Lonami <notifications@github.com>:
>Maybe I could make it in such a way that the default resources can
>**not** be modified, then use that file as a *template* and replace the
>strings with the translation.
>
>It probably is not that easy though, since chances are that the XML
>parser ignores empty lines and comments. I find myself writing an own
>parser-like class…
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/21#issuecomment-268646933

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
By the way, I know why the link confused me. You missed a `0` on the issue number, it's `100`, not `10`! 😳

**Comment by OffifialMITX** [comment]
Well that's strange because I've copied it from the URL bar using "Copy link". ¯\_(ツ)_/¯

**Comment by OffifialMITX** [comment]
I'm sorry anyway.

**Comment by XyLoNaMiyX** [comment]
Haha don't worry about it, I found what you meant so it's fine :)

**Comment by RomFouq** [comment]
Keeping the structure would really be handy; another example with [oandbackup](https://github.com/jensstein/oandbackup/blob/master/res/values/strings.xml), there are comments and blank lines to separate strings. But writing a brand-new parser isn't so easy and can bring some problems.

**Comment by XyLoNaMiyX** [comment]
> But writing a brand-new parser isn't so easy and can bring some problems.

Yes I know. And I'm having troubles to find something to only *edit* the XML while keeping the original file structure. There doesn't seem to be so many people interested about keeping the original structure out there either way.

**Comment by XyLoNaMiyX** [comment]
Not the best solution but it seems to work with the tests I've been doing. If anyone finds a bug with this solution, please drop a new issue.
