### ISSUE TITLE
Bug: Stringlate removes newlines in strings

### ISSUE THREAD

**Issue by NotSoImportant** [LonamiWebs/Stringlate#210]
Example:

```diff
-    <string name="contactMe">     Wenn Sie QuickDic benutzen, würde ich gerne von Ihnen hören.
-     Leider kann ich keine Verantwortung für die Wörterbücher (außer Formatierung) nehmen, weil sie aus anderen Quellen erzeugt werden.
-     Danke an Michael Vogel für Hilfe mit dem Icon und den deutschen Übersetzungen.
-     Bitte senden Sie Kommentare, Anregungen, Bug-Reports, oder einfach nur ein kurzes Hallo an:</string>
+    <string name="contactMe">Wenn Sie QuickDic benutzen, würde ich gerne von Ihnen hören.      Leider kann ich keine Verantwortung für die Wörterbücher (außer Formatierung) nehmen, weil sie aus anderen Quellen erzeugt werden.      Danke an Michael Vogel für Hilfe mit dem Icon und den deutschen Übersetzungen.      Bitte senden Sie Kommentare, Anregungen, Bug-Reports, oder einfach nur ein kurzes Hallo an:</string>
```

**Comment by Lonami** [comment]
I think the original string is, again, wrong. Newlines and leading whitespace should collapse into a single space. If you want a newline, you need to add `\n`, which is similar to #208.

**Comment by NotSoImportant** [comment]
The problem I see is Stringlate is editing stuff, I am not seeing is beeing edited, and probably also unwanted by the app developers I like to contribute to

**Comment by Lonami** [comment]
But… this seems like an issue on their end. I guess Stringlate could automatically add newlines on long strings, again, for readability purposes. Did they add newlines so that there are actual newlines, or so that it's readable?

There's another problem here, and it's we would need to analyze the "style" of the files to know what the developers would like! We can't keep everyone happy. What Stringlate should probably do though, is collapse `\n\s+` into a single `\s`, so you don't get those ugly `'      '` spaces.

**Comment by Lonami** [comment]
Stringlate is not "editing" stuff. You must bear in mind that this is a *new* translation (or an update for it), and sometimes there's no style information (e.g. new translations), or is inconsistent (e.g. default locale and translation have different styles) or the developer might just not care.

**Comment by Lonami** [comment]
Newlines indeed have no effect besides being more visually appealing:
![image](https://user-images.githubusercontent.com/6297805/39353476-16feb012-4a08-11e8-9ad9-bd793038bc86.png)

**Comment by NotSoImportant** [comment]
Thanks for trying that out and thanks explaining. 
The underlying problem I have with the approach you described before is that there is unexpected changes being committed.
