### ISSUE TITLE
AWESOME LOGO DESIGN FREE FOR YOU 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [LonamiWebs/Stringlate#217]
Hello, @LonamiWebsI want to contribute in "Stringlate" so i  want to designed a new logo for "Stringlate" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by Lonami** [comment]
You can design a new logo and propose it. If it goes well with the project and I'll like it then I'll consider using it. I'm not contacting you on facebook though. And of course you should be fine with the logo having the same license as the project.

**Comment by abdulmalikkhan655** [comment]
can i contribute in your app logo  if you give me permission i will send you my logo design

**Comment by Lonami** [comment]
You *can* make a logo, but remember we already have one:
![logo](https://github.com/LonamiWebs/Stringlate/raw/master/src/app/src/main/ic_launcher-web.png)

For your logo to be accepted it should follow Android style guidelines and look "better" than the current one.

**Comment by licaon-kter** [comment]
#198 🙄

**Comment by Lonami** [comment]
@licaon-kter [this comment](https://github.com/gsantner/memetastic/issues/100#issuecomment-389119668) is also relevant. I personally don't have any strong opinions for or against this… I mean if you want to make a logo you're free to do it, it's your time after all ¯\\\_(ツ)\_/¯.

**Comment by abdulmalikkhan655** [comment]
@Lonami  first of all open the my request then i will send you my logo design free of cost

**Comment by TacoTheDank** [comment]
@abdulmalikkhan655 why not just post it here? Youll get more feedback this way
