### ISSUE TITLE
app crash when click on start translating in landscape mode

### ISSUE THREAD

**Issue by kr-nahid** [LonamiWebs/Stringlate#219]
#### Expected behavior
user should be able to **start translating** in landscape mode without crash

#### Actual behavior
when i click on **start translating** in landscape mode it crash and i cant able to open it again 

#### How to reproduce
* download the app
* open the app
* click on add project
* rotate your phone protrait to landscape
* click on **start translating**
* note the bug

> Browser: 0.14
Operating system: android 5.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=YilH9JAUVyU

**Comment by Lonami** [comment]
Good news is I can reproduce the bug in current F-Droid's version, and it doesn't seem to happen in the master branch! Probably some of the changes @gsantner has been doing to the UI fixed the issue by chance.

**Comment by Lonami** [comment]
Oddly enough I'm retrying and I can't reproduce anymore :thinking:

**Comment by Lonami** [comment]
Thanks @gsantner for pointing out that the issue was *without* introducing any text.
