### ISSUE TITLE
Exit translation dialogue

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#22]
Now has:
* CANCEL - that does not save
* SAVE - that saves

I feel it's incomplete and confusing, say you hit back arrow by mistake then you can't cancel the dialogue, and if you hit the CANCEL button you actually erase you translated strings.

Better:
* CANCEL - cancel the dialogue
* DON'T SAVE - and exit translation
* SAVE - and exit translation

**Comment by XyLoNaMiyX** [comment]
Sorry for the problems this (probably) caused!

**Comment by licaon-kter** [comment]
It did not cause anything, as I just used the app to test the features and not to actually translate.
