### ISSUE TITLE
Show currenty unsaved strings number

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#23]
Change `SAVE` to `SAVE (4)` where 4 is the unsaved number of strings.

**Comment by XyLoNaMiyX** [comment]
What benefit would this bring? The whole file needs to be parsed when saving (it won't take longer if there is 1 change or if there are 100).

**Comment by licaon-kter** [comment]
So I have feedback.

**Comment by XyLoNaMiyX** [comment]
It actually looks fancier than I would have expected.

**Comment by licaon-kter** [comment]
I got this from Transifex.

**Comment by XyLoNaMiyX** [comment]
> I got this from Transifex.

It's a good place to take *"inspiration"* from… ( ͡° ͜ʖ ͡°)
