### ISSUE TITLE
Cannot login to github

### ISSUE THREAD

**Issue by ahangarha** [LonamiWebs/Stringlate#231]
Hi  
Just installed the app (tnz for this amazing work) and started translation of some app into Persian (Iran). But I cannot login to github.

I went to setting and in the place I should be able to tap login button, I don't see any button!

What should I do?

**Comment by Lonami** [comment]
Assuming you're using the latest version from F-Droid (currently `v0.15.1`), tap the ":heart: More" button at the bottom bar to the right, click on "Settings", and then select "Login to GitHub" under "User accounts". The notification could probably be clearer, or at least take you there. Cheers!

**Comment by ahangarha** [comment]
@Lonami I do exactly the same. But under "login to github" I see no button. Nothing happens by tapping on "login to github" as well!

I am using v.0.15.1 (1006).

**Comment by Lonami** [comment]
Strange, for me tapping there successfully logins.

**Comment by ahangarha** [comment]
As reference, you may look at [this screenshot](https://user-images.githubusercontent.com/11241315/41097255-8c9416f8-6a6c-11e8-8b33-514a04d8a759.png)

**Comment by licaon-kter** [comment]
Tapping that should open a web browser... Do you have a defaulhst browser? Try to change it, eg. It works here with Firefox

**Comment by ahangarha** [comment]
Yes. By default, all github links used to open in fasthub app. I just removed it as default and finally could get into firefox.
Tnx
Resolved

**Comment by Lonami** [comment]
Thanks @licaon-kter, saving the day ;)
