### ISSUE TITLE
Webview for help

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#24]
You already have internet access, use it.
Open a webview instead of a link in a browser, use the Spanish site if locale is Spanish and English for all others.

**Comment by XyLoNaMiyX** [comment]
I actually had thought of some markdown renderer view to provide offline help. But updated help would need to be downloaded anyway so this is also an option.

**Comment by licaon-kter** [comment]
Why bother when a webview is a given? Just pack that html page with the app.

**Comment by XyLoNaMiyX** [comment]
> Just pack that html page with the app.

True, just read I can load the HTML from a string.

**Comment by XyLoNaMiyX** [comment]
It wasn't as easy as it seemed at first!
