### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [LonamiWebs/Stringlate#26]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on Help icon
2. Orientation change

Sequence 2-4:
1. Click on Repository item in list
2. Click on ... (more options)
3. Click on:
a. Add New Locale
b. Delete - Delete locale
c. Delete - Delete repository
4. Orientation Change

**Comment by XyLoNaMiyX** [comment]
Could you please try this on any other application which also has a menu? This probably isn't related to Stringlate itself, but rather on how Android handles the menus.

Also, a rotation change when a menu is open should not happen too often to be considered an issue. It's fast to simply open it again (furthermore, the help dialog will be gone by the next release).

**Comment by reverse-unina** [comment]
Hi, thank you for the quick response.

I am a researcher exploring Android failures and I do tried on several apps. 
Mobile apps introduce the challenge to handle properly lifecycle events (e.g. orientation change, background-foreground or back button) and it may affect the user experience causing failures on GUI widgets (in this case a dialog) or app crashes (like the one in issue#28).

**Comment by reverse-unina** [comment]
As regards to dialogs I send you a pointer from Android guidelines.
Source: https://developer.android.com/guide/topics/ui/dialogs.html

The Dialog class is the base class for dialogs, but you should avoid instantiating Dialog directly[...]
[AlertDialog et al.] classes define the style and structure for your dialog, but you should use a **DialogFragment** as a container for your dialog. The DialogFragment class provides all the controls you need to create your dialog and manage its appearance, instead of calling methods on the Dialog object.

Using DialogFragment to manage the dialog ensures that it correctly handles **lifecycle events such as when the user presses the Back button or rotates the screen**.

**Comment by XyLoNaMiyX** [comment]
*Copy paste reply on all the related issues.*
Locking the orientation is the easiest fix, implemented on [commit#640706](https://github.com/LonamiWebs/Stringlate/commit/6407067b431263e6b33bf0103ba58ef8f51a95bd). Whenever someone complains they want to use Stringlate on landscape, or on a tablet device (which is not optimized for _at all_), then I might think on moving to fragments everywhere. Will be a pain if it happens.
