### ISSUE TITLE
Search widget disappear on orientation change

### ISSUE THREAD

**Issue by reverse-unina** [LonamiWebs/Stringlate#27]
When I perform these sequences of events, the search widget disappear and looses user input:

1. Click on Add New Repository
2. Click on Discover Repositories
3. Click on Search icon
4. Enter Text
5. Orientation Change

**Comment by licaon-kter** [comment]
"TheSerialRotator" hits again. :)

**Comment by XyLoNaMiyX** [comment]
I've just tried this with "*K-9 Mail*" (which also has a search on the action bar), and if the rotation changes, the input text is gone. Thus this "issue" is not related to Stringlate itself, but rather on Android.

However before I close this, why does rotation changes affect you so much @reverse-unina?

**Comment by reverse-unina** [comment]
You can try this on the best apps on Google App Store, too. 
Most of them does not lost the user input as it will affect the user experience.
Some of them still have this issue. We reported it and the dev team fixed it or opened an issue in order to fix it in the next releases

**Comment by licaon-kter** [comment]
Yes, this seems like a small issue, but it feels wrong, just because a lot of apps (or better said the libs or the implementations) have it does not help.

**Comment by XyLoNaMiyX** [comment]
> Yes, this seems like a small issue, but it feels wrong

I'm not willing to save the whole activity state only to fix this though (anyone can do that via `PR`). I will do take a look at what I can do and see if there is any simpler solution (I only had a quick look).

**Comment by reverse-unina** [comment]
Yes, indeed. Android Guidelines state to correctly manage these events. Simply because the interface should adapt to different orientation but not loose information. And there is no reason for the user to replay an action. It feels that Android Framework does not help developers in a simple way

**Comment by XyLoNaMiyX** [comment]
*Copy paste reply on all the related issues.*
Locking the orientation is the easiest fix, implemented on [commit#640706](https://github.com/LonamiWebs/Stringlate/commit/6407067b431263e6b33bf0103ba58ef8f51a95bd). Whenever someone complains they want to use Stringlate on landscape, or on a tablet device (which is not optimized for _at all_), then I might think on moving to fragments everywhere. Will be a pain if it happens.
