### ISSUE TITLE
Crash on orientation Change

### ISSUE THREAD

**Issue by reverse-unina** [LonamiWebs/Stringlate#28]
When I perform these sequences of events, the app crashes:

1. Click on Add New Repository
2. Click on Discover Repositories
3. Click on Refresh icon
4. Orientation change

**Comment by OffifialMITX** [comment]
Related: while translation any unsaved data gets lost when changing the prientation.

**Comment by XyLoNaMiyX** [comment]
*Copy paste reply on all the related issues.*
Locking the orientation is the easiest fix, implemented on [commit#640706](https://github.com/LonamiWebs/Stringlate/commit/6407067b431263e6b33bf0103ba58ef8f51a95bd). Whenever someone complains they want to use Stringlate on landscape, or on a tablet device (which is not optimized for _at all_), then I might think on moving to fragments everywhere. Will be a pain if it happens.

**Comment by Lonami** [comment]
By getting rid of the progress dialogs, the crash can't be a problem anymore. As the commit says more work needs to be done but this is the first step.
