### ISSUE TITLE
Text field lose user input on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [LonamiWebs/Stringlate#29]
When i perform this sequence of events, the text field returns empty:

1. Click on Repo item
2. Enter text in translated string
3. Orientation Change

**Comment by XyLoNaMiyX** [comment]
*Copy paste reply on all the related issues.*
Locking the orientation is the easiest fix, implemented on [commit#640706](https://github.com/LonamiWebs/Stringlate/commit/6407067b431263e6b33bf0103ba58ef8f51a95bd). Whenever someone complains they want to use Stringlate on landscape, or on a tablet device (which is not optimized for _at all_), then I might think on moving to fragments everywhere. Will be a pain if it happens.
