### ISSUE TITLE
Keep history

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#3]
...or show it, because now, on every app start I'm asked to search for a repo.

I should see those that I edited in the past (and that are theoretical on my device already) at start and make a "Translate another app" button maybe.

**Comment by XyLoNaMiyX** [comment]
If you start writing "ht…" on the URL field, it will suggest previous repositories. What other way to show them do you suggest? Maybe a 2-tabs layout, previous repositories and add repositories?

**Comment by licaon-kter** [comment]
Or that.

**Comment by XyLoNaMiyX** [comment]
Alright. My new idea is to have "Load repository — Add new repository — Discover" as three tabs in the main activity. What do you think?

**Comment by licaon-kter** [comment]
You mean Lo**cal** or Load ? Something that you point to a folder say on the SD card?

**Comment by XyLoNaMiyX** [comment]
I mean Lo**ad**. Load a *local* "repository" (the repository itself is not cloned, only the `strings.xml` files are downloaded), which you previously added and thus saved on the internal storage.

**Comment by XyLoNaMiyX** [comment]
I hope you like the new layout, any feedback about it is appreciated!

**Comment by OffifialMITX** [comment]
Maybe some icons would make evrrything even prettier.

**Comment by XyLoNaMiyX** [comment]
Yeah I thought that too but that would involve scanning the GitHub repository of the application (I can't depend on the F-Droid repository; the application you're translating might not be there).

Also, although the application icon is usually stored as `ic_launcher.png`, it might not be necessarily the case. Furthermore the GitHub API doesn't have an option to search for a file (when I look for the `strings.xml` files, I actually cheat a bit and use the *search in the file contents* because the word `resources` is always on the `strings.xml` file).

Maybe I could sneak the `AndroidManifest.xml` and see the `android:icon="@mipmap/ic_launcher"`… Anyway, not a priority.

**Comment by XyLoNaMiyX** [comment]
@OffifialMITX, remember this?:
> Maybe some icons would make evrrything even prettier.

Well, since I clone the repository I can now save that. Done on [commit#848cba](https://github.com/LonamiWebs/Stringlate/commit/848cbac73f3cb2187eb5e0c71edc483d59f79c7c).

**Comment by OffifialMITX** [comment]
I don't understand, what do you mean?

**Comment by XyLoNaMiyX** [comment]
> I don't understand, what do you mean?

I mean I've added icons on the home screen, just like you wanted @OffifialMITX:
![New screenshot 1](https://raw.githubusercontent.com/LonamiWebs/Stringlate/848cbac73f3cb2187eb5e0c71edc483d59f79c7c/resources/screenshots/s1.png)

**Comment by OffifialMITX** [comment]
Oh cool!

**Comment by XyLoNaMiyX** [comment]
> I don't think that the ".com" after GitHub and GitLab is actually needed.

It's the full host. An application may be hosted at an `.org` or `.net` host. Anyway, the `.com` is a useful as the GitHub part (nothing at all), so I don't mind it being there.

**Comment by OffifialMITX** [comment]
You're actually right.

Am 15. Januar 2017 17:06:05 MEZ, schrieb Lonami <notifications@github.com>:
>> I don't think that the ".com" after GitHub and GitLab is actually
>needed.
>
>It's the full host. An application may be hosted at an `.org` or `.net`
>host. Anyway, the `.com` is a useful as the GitHub part (nothing at
>all), so I don't mind it being there.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/3#issuecomment-272704499

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by OffifialMITX** [comment]
Can you please upload a screenshot with a larger resolution so I have something to work with? 480x854 would be enough.

**Comment by XyLoNaMiyX** [comment]
@OffifialMITX 
![screenshot_20170115-140042](https://cloud.githubusercontent.com/assets/6297805/21965920/91db0966-db69-11e6-9b19-2a85c0708534.png)

**Comment by OffifialMITX** [comment]
What font is actually used?

**Comment by OffifialMITX** [comment]
Here are the first two, the third one belongs to the UI improvement and comes a bit later:
![test1 5](https://cloud.githubusercontent.com/assets/22666602/21966355/e3e37f2e-db71-11e6-8c93-8efdf035d27e.png)

**Comment by XyLoNaMiyX** [comment]
I did think about both options. However:
1. In the first one, I would still like to see the host somewhere (GitHub, GirLab, etc.).
2. In the second one, perhaps it would look a bit crazy since _all_ the repositories would show some background at probably different % each.

Also, maybe the selected locale in the top right corner of each item (like for example "(es)") would look good.

**Comment by OffifialMITX** [comment]
Good arguments but:
1. In my opinion it's not necessary to know which host an application belongs to for it's translating. I will try how a vertical bar looks like in the next few days.
2. You're actually right, that's what I thought either, but maybe this is how it could look like in the desktop application when the mouse focuses on it.

Yes, :+1: for the selected locale

I still have some things on my might, containing mainly progress % view, start menu UI and the design of the translator *(I have a basic Idea how it could be optimized for larger strings but I have to think about it a little more)* and I'll try to put everything on pictures until the end of the next week.
