### ISSUE TITLE
Spinner and Text change state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [LonamiWebs/Stringlate#30]
When I perform this sequence of events, the spinner Current String and Original String Textview chenge state

Precondition 1: There are more two or more strings not yet translated

1. Click on repo item
2. Select current string ID from the spinner
3.  Orientation Change 

Note: IF Show translated strings is checked, after the orientation change it becomes unchecked

**Comment by XyLoNaMiyX** [comment]
*Copy paste reply on all the related issues.*
Locking the orientation is the easiest fix, implemented on [commit#640706](https://github.com/LonamiWebs/Stringlate/commit/6407067b431263e6b33bf0103ba58ef8f51a95bd). Whenever someone complains they want to use Stringlate on landscape, or on a tablet device (which is not optimized for _at all_), then I might think on moving to fragments everywhere. Will be a pain if it happens.
