### ISSUE TITLE
Repositories outside Github

### ISSUE THREAD

**Issue by kelna** [LonamiWebs/Stringlate#31]
Please make it possible to use repos outside Github.

**Comment by XyLoNaMiyX** [comment]
Apart from GitLab, do you know any other? They also need to have some kind of API or I wouldn't be able to do that much (perhaps cloning the repository if it hadn't API, but that would be a bit overkill).

**Comment by kelna** [comment]
Gitlab would be the most important (e.g. F-droid uses that) but there are others too:
freedesktop.org (e.g. LibreOffice Viewer)
sourceforge.net (e.g. Open Camera)

And there are self-hosted projects like Orbot (torproject.org).

**Comment by XyLoNaMiyX** [comment]
Then for further reference I probably need to borrow some files from [Agit](https://github.com/rtyley/agit) or [MGit](https://github.com/maks/MGit), and better remember to use their `git clone --depth 1` equivalent to avoid cloning the whole history.

**Comment by XyLoNaMiyX** [comment]
I tested with F-Droid itself but it has a bunch of different files containing "`<string`" and Stringlate doesn't yet know which one it should choose - but it works, and it's hosted on GitLab which is the point :)

**Comment by kelna** [comment]
Great job! :)
