### ISSUE TITLE
Translation field and keyboard interaction

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#33]
Using the Google Keyboard (ie new Gboard) or any other, I have the "auto-capitalize" on, yet the translation field does not trigger that.

**Comment by XyLoNaMiyX** [comment]
Fast enough service? ;)

Solution found [here](http://stackoverflow.com/a/4808749/4759433), for further reference.

**Comment by licaon-kter** [comment]
8 minutes? That's slow... :)
