### ISSUE TITLE
Deleting translated strings should be detected

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#34]
And translated strings number counter updated -1

Yes, saving, exit, re-enter and you get the correct count.

**Comment by XyLoNaMiyX** [comment]
> And translated strings number counter updated -1

The counter is indeed updated? Can you give me steps to reproduce? I type something, click on `Delete > String` and the translated count decreases.

**Comment by XyLoNaMiyX** [comment]
> ### Deleting translated strings should be detected

And do you mean the `Save (n)` button? That shouldn't be indeed updated, because the value is different. Could you please be a bit more specific?

**Comment by licaon-kter** [comment]
It's the F-Droid version, no Save (x) yet.

So, open a string, look below to see 34/123, start writing, see 35/123, delete text, nothings happens, still 35/123. Go back to projects, re open, see correct 34/123.

**Comment by XyLoNaMiyX** [comment]
Alright I see your point.
