### ISSUE TITLE
Add czech translation

### ISSUE THREAD

**Issue by rr-vesp** [LonamiWebs/Stringlate#37]
Hi, I created czech (cs_CZ) translation using your great app. Here is it: https://gist.github.com/anonymous/babda058695b86512d7d67a42e8e5d23

I hope that everything is OK, I am new to GitHub.

**Comment by XyLoNaMiyX** [comment]
Thanks for the feedback and for the translation. Everything is OK too, and last but not least welcome to GitHub :)

**Comment by XyLoNaMiyX** [comment]
Hello @rr-vesp would you mind updating your translation before the next `v0.9.5` release? You can either [translate this Gist](https://gist.github.com/XyLoNaMiyX/4aaab46a17514fb19d1ff1f0580dded9) or use Stringlate itself! Thank you.

**Comment by rr-vesp** [comment]
Hi, I created [issue](https://github.com/LonamiWebs/Stringlate/issues/56) with an update.
