### ISSUE TITLE
Sort locale list

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#38]

**Comment by XyLoNaMiyX** [comment]
Maybe even icons for the locales or the full locale name. This can be done because Android already embeds a map-like from locale code to name. Opinion?

**Comment by licaon-kter** [comment]
Full locale would be nice.

**Comment by licaon-kter** [comment]
Not sure how full locale get selected, but now the mapping seems random, eg.
* `de` ends up as Swiss
* `es` as Bolivia
* `ro` as Moldavia
* `ca` as France
* `sv` as Finland

And so on.

**Comment by XyLoNaMiyX** [comment]
> Not sure how full locale get selected, but now the mapping seems random, eg.

Version and application you tested this on @licaon-kter?

**Comment by licaon-kter** [comment]
0.95 on https://github.com/lonamiwebs/stringlate :)

**Comment by XyLoNaMiyX** [comment]
I've just tried it and I don't get your random results.

**Comment by XyLoNaMiyX** [comment]
Maybe. The way I determine the display is via the [`LocaleString.java`](https://github.com/LonamiWebs/Stringlate/blob/master/src/app/src/main/java/io/github/lonamiwebs/stringlate/classes/LocaleString.java#L24-L37), and I cannot see anything suspicious there.

**Comment by licaon-kter** [comment]
What mappings do you get, eg: de ( ?????? ) and ro ( ?????? ) ?

**Comment by XyLoNaMiyX** [comment]
With this code:
```java
String[] test = new String[] {"de", "es", "ro", "ca", "sv"};
for (String t : test)
   Log.i("TEST", "FOR LOCALE "+t+" GOT DISPLAY "+LocaleString.getDisplay(t));
```

I get these results:
```
FOR LOCALE de GOT DISPLAY German
FOR LOCALE es GOT DISPLAY Spanish
FOR LOCALE ro GOT DISPLAY Romanian
FOR LOCALE ca GOT DISPLAY Catalan
FOR LOCALE sv GOT DISPLAY Swedish
```

On both the latest commit and the `v0.9.5` tag.

**Comment by licaon-kter** [comment]
Ok, so Nougat has a `language ( Country )` mapping now in `Languages and Input` and for one language you can have multiple countries, apparently Stringlate gets the first country as sorted.

I guess you could test this in AndroidStudio->Emulator by simulating a Nougat device ?!

**Comment by XyLoNaMiyX** [comment]
> Ok, so Nougat has a `language ( Country )` mapping now in `Languages and Input` and for one language you can have multiple countries, apparently Stringlate gets the first country as sorted.

Uhm… I'm slightly confused, not gonna lie. Also, emulating a Nougat device on *my* laptop with *Android Studio open* too? I would really appreciate if you submit a patch for this! :S

Also, I think it's better to open a new issue since you've confirmed the bug on Nougat.
