### ISSUE TITLE
Translation field as multiline

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#39]
The original string has that.

But the translation field does not, making it fiddly at least.

**Comment by licaon-kter** [comment]
Hehe, funny story, thanks for this, but I wanted something else and I failed to say that.

Yes multiline was need (it was in my mind for a future issue as soon I dig up a repo with such a string), but I actually wanted line wrapping. :)

Not sure if this covers that too.

**Comment by XyLoNaMiyX** [comment]
What do you mean by line wrapping? Scrollable `EditText`? It will grow, there won't be a scrollbar for it but rather for the whole layout. Also, Android wrapping defaults to word break I think? (There is no horizontal scroll).

**Comment by licaon-kter** [comment]
Umm, currently it scrolls horizontally, no matter how much text you have it's only one line.

**Comment by XyLoNaMiyX** [comment]
Open a new issue if it happens by the next release.
