### ISSUE TITLE
Sort by string length

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#41]
Did not see this elsewhere either, the idea is that since every little project can have lots of strings (eg. Stinglate has >110 OMFG!) it will get boring after a while, so it helps me seeing that I translated a lot of them. ;)

Having them sorted by length helps me get the shorter ones faster, keeping my interest strong.
I already do this by just skipping long ones until they're the only ones left.

**Comment by XyLoNaMiyX** [comment]
> it will get boring after a while

Yeah, I even thought of making Stringlate game-like but I don't know how a game of *translating strings* could look like…

> Having them sorted by length helps me get the shorter ones faster, keeping my interest strong.

Sorting by length vs sorting alphabetically (the change isn't hard at all). But what will happen when only the long ones are left?: "Oh darn, 50 strings left… and *every string* will be as long *or even longer* than the previous one!"

**Comment by licaon-kter** [comment]
You have to *translate them all!* anyway, long or short, that does not make a difference. ;)

**Comment by XyLoNaMiyX** [comment]
> anyway, long or short, that does not make a difference.

Conclusion then? The badges idea sounded fancy though!

**Comment by licaon-kter** [comment]
Did not answer the *gamification* thing because I don't care, better open another issue with that to see if anyone cares. :)

**Comment by XyLoNaMiyX** [comment]
Is this still relevant @licaon-kter or kinda solved since the progress bar is now weighted?

**Comment by licaon-kter** [comment]
I would still like it, if it's not hard, if you want etc.

**Comment by XyLoNaMiyX** [comment]
You know though. My first impression of this was that you only wanted sorting by string length instead alphabetically. But you really meant to have it as a setting, for people to choose. The later makes way more sense.

**Comment by licaon-kter** [comment]
Thanks
