### ISSUE TITLE
Don't show features not yet implemented

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#43]

**Comment by XyLoNaMiyX** [comment]
I left it there to get people excited! Hopefully it will *be* implemented by the next version.

**Comment by licaon-kter** [comment]
Yeah, I felt "disappointment" more than "excitement" :)

Wonder how you would make things work when the user already has the project repo forked on GitHub and some commits over that.

**Comment by XyLoNaMiyX** [comment]
> Wonder how you would make things work when the user already has the project repo forked on GitHub and some commits over that.

Now I'm the disappointed one, I thought things would be easier! I also thought that maybe I could make use of the "Suggest edit" feature that GitHub offers. Not sure if that is available on all the repositories; and maybe I don't need to clone to create a pull request.

**Comment by licaon-kter** [comment]
Not sure if that's another thing than "Edit" since that one forks the repo in the background and then you edit.

**Comment by XyLoNaMiyX** [comment]
[Now it is implemented](https://github.com/LonamiWebs/Stringlate/issues/19#issuecomment-269809589).
