### ISSUE TITLE
Always show icons for locally installed apps

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#45]
Can the icons be loaded from local resources so they'll not use the internet?

**Comment by XyLoNaMiyX** [comment]
> Can the icons be loaded from local resources so they'll not use the internet?

Yes, they can. Maybe the icon downloader can first check if the application is installed and then somehow cache it differently (querying the icons is slow). I copied the code for lazily loading the icons, but I could add that.
