### ISSUE TITLE
Search app description and app Android name too

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#47]
This expands the discovery goal a bit too.

**Comment by XyLoNaMiyX** [comment]
Thing is that I don't save the description so it takes even less space when downloaded. Is it worth to add looking for description?

**Comment by licaon-kter** [comment]
I see some sort of description in the app list (so you have it), not sure how you call that, but do search it.

**Comment by XyLoNaMiyX** [comment]
Ah you mean the *summary*, not the full *description* (I thought that's how they were called). Alright then.

**Comment by licaon-kter** [comment]
The yeah, whatever, use it! :)

**Comment by XyLoNaMiyX** [comment]
Yes boss.
