### ISSUE TITLE
Some strings.xml files are missed if there are ≥ 30 locales

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#48]
https://github.com/M66B/NetGuard

So...
* every time I open this repo I get the "no strings do refresh" toast, and I need to refresh
* after refresh `ro` is not available in the dropdown
* hittings refresh a second time freezes the app

**Comment by XyLoNaMiyX** [comment]
For some incredibly strange reason, I can't find the path for the default `strings.xml` file! Besides, these files contains several `<string-array>` tags which, well, are not yet supported. But this should not affect the file not being downloaded…

**Comment by licaon-kter** [comment]
_wrong button_

Counting directly I see 45 locales, while the app loads 30.

**Comment by XyLoNaMiyX** [comment]
> Counting directly I see 45 locales, while the app loads 30.

Yes, I was just checking that indeed. However, the [resulting JSON](https://gist.github.com/XyLoNaMiyX/f370f471c548ffa3eac61de393070a7e) that Stringlate downloads says `"incomplete_results": false,`, when it clearly is incomplete.

**Comment by licaon-kter** [comment]
is 30 a magic number? I see this on another repo ( #51 ) too, and it has 33 locales, yet it says it loads only 30, and my `ro` is not one of them. :(

**Comment by XyLoNaMiyX** [comment]
My bad, I forgot to add the "closes #48" on the [commit#921f20](https://github.com/LonamiWebs/Stringlate/commit/921f20943f35e8dbf358cb4642b290f185f93b47). Anyway after a few headaches that's fixed :)
