### ISSUE TITLE
Repo links incomplete

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#49]
Like I2P has in the index, not sure how your app should handle these.

I'll add a MR to (maybe) fix this on F-Droid.

**Comment by XyLoNaMiyX** [comment]
> Repo links incomplete

What links?

> I2P

What is I2P?

**Comment by licaon-kter** [comment]
Use your app and search for "i2p" :)

**Comment by XyLoNaMiyX** [comment]
Alright, this issue is not related to Stringlate itself. Given a GitHub owner only (as I2P does), I can't directly tell in which of their repositories the wanted application resides.

**Comment by XyLoNaMiyX** [comment]
The best I can do is hiding it from the *Discover* activity.
