### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#5]
https://gist.github.com/f681245a7522e9c5ba3b7be1bcb36c17

**Comment by XyLoNaMiyX** [comment]
Thank you! Will merge ASAP.

**Comment by XyLoNaMiyX** [comment]
@OffifialMITX could you please translate these 9 strings?:
```<resources>
    <string name="add_new_repo">Add new repository</string>
    <string name="apps_repo_not_downloaded">The applications repository has not been downloaded yet. Tap the \"%s\" menu button to download the repository index in order to explore all the available applications.</string>
    <string name="discard_changes">Discard changes</string>
    <string name="keep_changes">Keep changes</string>
    <string name="files_modified_keep_changes">Some resource files were modified. Do you wish to keep your local changes along with the remote modifications, or discard all your changes?</string>
    <string name="history">History</string>
    <string name="history_no_repos_hint">New here? Head to the \"%s\" tab to get started!</string>
    <string name="history_contains_repos_hint">These are your previously synchronized repositories. Select one below or add a new one to continue.</string>
    <string name="repositories_colon">Repositories:</string>
</resources>
```

**Comment by XyLoNaMiyX** [comment]
Never mind anymore, sorry to bother you!

**Comment by OffifialMITX** [comment]
Oh, don't worry, I was just the whole day away fom my wifi, translation comming soon if you still want.

**Comment by OffifialMITX** [comment]
`<resources>
<string name="add_new_repo">Neue Quelle hinzufügen</string>
<string name="apps_repo_not_downloaded">Die Applikationsquelle wurde noch nicht heruntergeladen. Clicken Sie den \"%s\" Menu knopf um die Anwendungsliste zu aktualisieren, damit sie neue Quellen entdecken können.</string>
<string name="discard_changes">Änderungen verwerfen</string>
<string name="keep_changes">Änderungen beibehalten</string>
<string name="files_modified_keep_changes">Einige Quelldateien wurden modifiziert. Wollen Sie die Lokalen Änderungen neben den entfernten Modifizierungen beibehelten oder sie löschen?</string>
<string name="history">Geschichte</string>
<string name="history_no_repos_hint">Neu hier? Gehen Sie zu der \"%s\" Zeile um loszulegen!</string>
'<string name="history_contains_repos_hint">Hier sind Ihre letzten synchronisierten Quellen. Wählen Sie eine dieser aus oder fügen Sie eine neue hinzu, um fortzufahren.</string>
<string name="repositories_colon">Quellen:</string>
</resources>`

**Comment by OffifialMITX** [comment]
Sorry, I have no idea how to make the code look nice :'(

**Comment by XyLoNaMiyX** [comment]
I already had them, that's why I said never mind! 😳 Anyway thanks!

You can make the code nice by putting the language after the three `, in your case xml.

**Comment by OffifialMITX** [comment]
Oh, thanks, good to know.

Am 19. Dezember 2016 08:20:30 MEZ, schrieb Lonami <notifications@github.com>:
>I already had them, that's why I said never mind! 😳 Anyway thanks!
>
>You can make the code nice by putting the language after the three `,
>in your case xml.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/5#issuecomment-267897956

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by OffifialMITX** [comment]
I've used "Quelle" for "repository" while the other just used "Repository".

Both are correct but it could be easily missunderstoodable if there are 2 different words in different buttons/describings.

I've reworked my <a href"https://gist.github.com/329b07f02434a7fcff18e6294907a98c">translation</a> changing what I already described and some of my faults I didn't notice before.

Am 19. Dezember 2016 08:20:30 MEZ, schrieb Lonami <notifications@github.com>:
>I already had them, that's why I said never mind! 😳 Anyway thanks!
>
>You can make the code nice by putting the language after the three `,
>in your case xml.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/5#issuecomment-267897956

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
Right now I'm in a weird situation. I have both you and someone else helping out on the German translations and I thank you both, but I don't really know what to do!

I was waiting a bit until I had all the strings for the next version before I actually made any commit (otherwise I'll have a lot of commits and all changing the strings, I don't want to bloat the history). So we'll see what we do with the German strings.

**Comment by OffifialMITX** [comment]
For me it's ok if you replace every "Quelle" with "Repository", I just don't want different expressions for the same thing.

Am 21. Dezember 2016 07:34:14 MEZ, schrieb Lonami <notifications@github.com>:
>Right now I'm in a weird situation. I have both you and someone else
>helping out on the German translations and I thank you both, but I
>don't really know what to do!
>
>I was waiting a bit until I had all the strings for the next version
>before I actually made any commit (otherwise I'll have a lot of commits
>and all changing the strings, I don't want to bloat the history). So
>we'll see what we do with the German strings.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/5#issuecomment-268448061

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
Alright, I've used `nexx`'s strings where "Quelle" appeared to keep consistency with "Repositories" as well. When adding the few missing strings, I've checked them out first to see which one seemed to fit more in the application and used your translation @OffifialMITX for some strings and his for others.

Sounds fair enough to me, now I feel (a bit) less guilty for having you both working on the translation!

**Comment by OffifialMITX** [comment]
Here it goes again:

https://gist.github.com/4cc68a1e712769be9010cdfde6ca81ae

**Comment by XyLoNaMiyX** [comment]
Hello @OffifialMITX would you mind updating your translation before the next `v0.9.5` release? You can either [translate this Gist](https://gist.github.com/XyLoNaMiyX/4aaab46a17514fb19d1ff1f0580dded9) or use Stringlate itself! Thank you.

**Comment by OffifialMITX** [comment]
Yeah, sure.

Am 30. Dezember 2016 20:47:19 MEZ, schrieb Lonami <notifications@github.com>:
>Hello @OffifialMITX would you mind updating your translation before the
>next `v0.9.5` release? You can either [translate this
>Gist](https://gist.github.com/XyLoNaMiyX/4aaab46a17514fb19d1ff1f0580dded9)
>or use Stringlate itself! Thank you.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/5#issuecomment-269814062

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by OffifialMITX** [comment]
Here it goes: https://gist.github.com/491c20fc47624e7badbcaabf6bd94690

**Comment by XyLoNaMiyX** [comment]
That was fast, thanks a lot and sorry if the message sounded rude!

**Comment by OffifialMITX** [comment]
Don't worry, I like helping others and that didn't sound rude for me. Happy new year!

Am 30. Dezember 2016 22:18:31 MEZ, schrieb Lonami <notifications@github.com>:
>That was fast, thanks a lot and sorry if the message sounded rude!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/5#issuecomment-269823112

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
Happy new year :)

**Comment by OffifialMITX** [comment]
https://gist.github.com/584e5412a56f96f958721b4864d7e105

Am 30. Dezember 2016 22:18:31 MEZ, schrieb Lonami <notifications@github.com>:
>That was fast, thanks a lot and sorry if the message sounded rude!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/5#issuecomment-269823112

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
