### ISSUE TITLE
Repo with multiple resource places issues

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#51]
Eg: https://github.com/siacs/Conversations/ ( has actual strings here: https://github.com/siacs/Conversations/tree/master/src/main/res )

But, it includes a custom lib: https://github.com/siacs/Conversations/tree/master/libs/MemorizingTrustManager (which has its resources here: https://github.com/siacs/Conversations/tree/master/libs/MemorizingTrustManager/res )

Now, your app gets confused:
* locale selector has 30 options (ahem #48) from the main app
* strings are actually from lib/MTM, aka only 11 strings

**Comment by XyLoNaMiyX** [comment]
Darn why do you always want to translate the repositories which more problems have‽ ;)

First of all, quoting from their [README.md](https://github.com/siacs/Conversations/blob/master/README.md) on this specific case:
> #### Translations
> Translations are managed on [Transifex](https://www.transifex.com/projects/p/conversations/)

Secondly, I don't know of any reliable way for telling which strings should be translated. Any idea on how I could possibly handle this? Make sure that the parent repository matches? And then what?

> locale selector has 30 options

Third, maybe this is some GitHub limit. But again, it should say `"incomplete_results": true` but it says `"incomplete_results": false`. An option would be to ensure that the length of the array matches, otherwise… I don't quite know.

**Comment by licaon-kter** [comment]
I already translated that app via Transifex ;)

I just wanted to see if your app loads it fine...

**Comment by XyLoNaMiyX** [comment]
Alright, any idea on what I could do to distinguish between the string files though?

**Comment by licaon-kter** [comment]
One idea: how does gradle/AndroidStudio decides?

**Comment by XyLoNaMiyX** [comment]
> how does gradle/AndroidStudio decides?

Several `build.gradle` files, but not all projects are built by using Gradle. Those which do have the following lines (I assume):
```gradle
apply plugin: 'com.android.application'
apply plugin: 'com.android.library'
```

But what if you want to translate a library or something?

**Comment by XyLoNaMiyX** [comment]
Just to leave some feedback and to solve a few issues in a row, I will clone the whole `git` repository (this solves: **1.** Too many files for the GitHub API to return; **2.** Support for any `git` site).

This will also allow me to **3.** look for `.xml` files *and* their contents to ensure they contain `<string>` or `<string-array>`.

To handle multiple files, I probably save the resources as follows: `Project` -> `Resources`, with `remotePath` -> `Strings` thus fixing **4.**, multiple files.

For further reference on how I to use `git` from Android, I will be using `org.eclipse.jgit` in the same way [APDE](https://github.com/Calsign/APDE/tree/master/APDE/src/main/java/com/calsignlabs/apde/vcs) does.

**Comment by XyLoNaMiyX** [comment]
Better way to handle multiple files: *only* the default resources will have multiple files and these will remain **untouched**. The remote paths will be stored in a custom `settings.json` for the default locale, and from there we'll also be able to determine the remote path for the other locales.

Internally, Stringlate will use a single big file for all the other locales, and when exporting, then it *will* make use of all the files. It will take a file, apply the template by replacing the found IDs, and repeat with the other files.

**Comment by XyLoNaMiyX** [comment]
Done with commit [#70aea6](https://github.com/LonamiWebs/Stringlate/commit/70aea62a97c9094c9e8700746e9693e9b232c8b4), I think.
