### ISSUE TITLE
Repo with strings outside the src folder

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#52]
Eg: https://github.com/vanilla-music/vanilla yields "no strings.xml found"

**Comment by XyLoNaMiyX** [comment]
Indeed, the repository doesn't have any `strings.xml` file. It has `translatable.xml`. The `strings.xml` files contain `<resources>`, but this is not limited to `<string>` (there are other files that have `<resources>`, but don't have any `<string>`).

Suggestions? Search for `resources string` instead, despite the file name? How can I tell it's a file containing strings reliably then?

**Comment by XyLoNaMiyX** [comment]
(Furthermore they use [Transifex](https://www.transifex.com/projects/p/vanilla-music-1/) as well).

**Comment by licaon-kter** [comment]
Yes, indeed.

Regarding external translations sites, I see that even when those exist there are users that choose to translate strings.xml directly, say to see how the git/github workflow works or find it easier like that. And devs will use those translation, and rightly so, that work is useful.

**Comment by licaon-kter** [comment]
And another one: https://github.com/SufficientlySecure/document-viewer

**Comment by XyLoNaMiyX** [comment]
> And another one: https://github.com/SufficientlySecure/document-viewer

Well that one is crazy. I didn't even know *that* was possible. How would Stringlate possibly handle that? Merge all the strings into one big internal file and when exporting exporting to multiple files…?

---

So, one way to fix the Vanilla case is to use another search filter that doesn't require the filename to be `strings.xml`. **Problem**, more files which are *not* files containing strings get included. I would need to download those too and inspect their contents to make sure it's a valid strings file.

**Comment by licaon-kter** [comment]
Ok, thinking about this, better just give up.

Instead of showing that _"there is no strings.xml"_ toast (actually you know the strings are somewhere, that's a given, right?) better pop-up a dialogue saying: _"hey, no can do, I can't find strings.xml, but please here's the repo link: github.com/author/project, open it in a browser, find the values folder and copy the link to whatever that strings file is, paste it below"_ and you offer an input text field.

Now with that link, you go and setup a new locale, and translate that, save that. Better than nothing. Yes more coding. :(

**Comment by XyLoNaMiyX** [comment]
> find the values folder and copy the link to whatever that strings file is, paste it below" and you offer an input text field

`*`User opening *document-viewer* repository`*`: Hey I found 15 `strings.xml` files… What, what am I supposed to do here?

*Under this extreme situation, Stringlate should offer Superman's phone number or something for him to solve the problem…*

**Comment by licaon-kter** [comment]
New dialogue: _"Still can't find it? Better ask the dev to layout its project better, if s/he wants translations"_

Actually an user needs to know a lot just to get there anyway, GitHub, repos, Gist, PR... it's not a newbie up to this point, I guess.

**Comment by XyLoNaMiyX** [comment]
> *"Still can't find it? Better ask the dev to layout its project better, if s/he wants translations"*

Lmao. Anyway, Stringlate abstracts the GitHub thing a lot, the user doesn't necessarily need to know how the work flow is like here. But I don't think making the user look for a file is the right way to do this. They shouldn't need to know how Android projects are (*usually*) structured. Not even an option of "Hey I found this and this path for the strings. Which one is?" sounds right.

**Comment by licaon-kter** [comment]
Then I don't know, this feels like it needs a human or some AI to sort (an otherwise) simple matter.

**Comment by XyLoNaMiyX** [comment]
Starts with an application to translate strings, ends with an AI that dominated the whole world. People get ready for StrAI. I think I should just tag this as `help-wanted` and #hope.

**Comment by licaon-kter** [comment]
You were lost when you decided to write the app instead of just translating that other app and carry on. :)

**Comment by XyLoNaMiyX** [comment]
> You were lost when you decided to write the app instead of just translating that other app and carry on. :)

I actually wrote the application far after I did the translation by hand, but I'm still happy with this work ;)
