### ISSUE TITLE
String-arrays missing

### ISSUE THREAD

**Issue by kelna** [LonamiWebs/Stringlate#53]
I translated Face Slim and I did everey string but there are still untouched strings inside string-arrays. Check this:
https://github.com/indywidualny/FaceSlim/blob/master/app/src/main/res/values/strings.xml#L21-L32

Stringlate overlooks the string-array part.

**Comment by XyLoNaMiyX** [comment]
I'm [aware](https://github.com/LonamiWebs/Stringlate/issues/48#issuecomment-269502331) of this lack of implementation. Thanks for posting it here for me to remember I have to fix it though!

Worst part with this problem is that I have a custom XML serializer (for people not to complain about their `strings.xml` structure being messed up). So I have to both think a way at how I could store this internally and how I should show it to the user, although I have a vague idea.

**Comment by licaon-kter** [comment]
Could you (for now) just ignore/skip them?

I see they end up in the translation (although I did not translate them), funny that one with `translatable=false` is there too.

**Comment by XyLoNaMiyX** [comment]
> I see they end up in the translation (although I did not translate them)

Which do? The one insides the `<string-array>`? I can't see them

> funny that one with `translatable=false` is there too.

I can't find that either from Stringlate. Are you sure they're included?

**Comment by licaon-kter** [comment]
Just did Pedometer and I had to use Meld to merge the origial and my translated, and I had these too.

**Comment by licaon-kter** [comment]
There's no shortage of bugs reported... BTW, any chance of another point release so we can test the changes?

**Comment by XyLoNaMiyX** [comment]
> so we can test the changes?

Which changes do you want to test? I can provide a build right now if you wish.

**Comment by licaon-kter** [comment]
I can build, was thinking to push a tag for F-Droid to catch to users out there. ;)

**Comment by XyLoNaMiyX** [comment]
@kelna or @licaon-kter I would like to ask, do you have any idea on how I could present the `string-array`'s or `plurals` to the user?

**Comment by licaon-kter** [comment]
Arraytitle>string1
Arraytitle>string2

So there's some context.

**Comment by XyLoNaMiyX** [comment]
I thought exactly that, and since I need something similar for the `plurals`, maybe simply a `TextView` indicating `#1`, `#2` for the `string-array` and `quantity` for the `plurals` is the best solution.

**Comment by XyLoNaMiyX** [comment]
Done on [#131a55](https://github.com/LonamiWebs/Stringlate/commit/131a551df8f9138aef9033e6cdbb31311df6c53d), [#b660fb](https://github.com/LonamiWebs/Stringlate/commit/b660fb3d5ed21eef924a0da5125ae8b33b5e8eef) and [#70aea6](https://github.com/LonamiWebs/Stringlate/commit/70aea62a97c9094c9e8700746e9693e9b232c8b4).
