### ISSUE TITLE
Lines without closing </string>

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#54]
Like: https://github.com/SecUSo/privacy-friendly-pedometer/blob/master/app/src/main/res/values/strings.xml#L238

Are these valid? The app just adds an ending `</string>` now.

**Comment by XyLoNaMiyX** [comment]
> Are these valid?

As valid as useless. Android studio doesn't seem to complain (they're valid xml tags) so they probably left it there accidentally. `<string />` is the same as `<string></string>`, so no problem with that :)

I will ignore the empty strings so they are not included in the translation process.

This made me notice some other issue though, the new way I have to determine if it is a valid repository seems to be skipping quite a few valid apps, so thanks for that. It's fixed now.
