### ISSUE TITLE
Strings with front spaces 

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#55]
Like: https://github.com/SecUSo/privacy-friendly-pedometer/blob/master/app/src/main/res/values/strings.xml#L224

That's actually `SPACE(active)` but the app erases the space in the field.

**Comment by XyLoNaMiyX** [comment]
Yeah, I told her on the PR I made. I think she needs to put the string between quotes like `" (active)"` or Android will trim it. Not sure if it's Android, or when building the application, but this is not related to Stringlate.

All I know is that if I leave a trailing space on the translation manager Android Studio provides, it automatically gets quoted.
