### ISSUE TITLE
Full locale mapping issue on Nougat

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#58]
Not sure how full locale get selected, but now the mapping seems random, eg.
* `de` ends up as Swiss
* `es` as Bolivia
* `ro` as Moldavia
* `ca` as France
* `sv` as Finland

And so on.

Ok, so Nougat has a `language ( Country )` mapping now in `Languages and Input` and for one language you can have multiple countries, apparently Stringlate gets one of those, not sure on what rule exactly.

**Comment by XyLoNaMiyX** [comment]
Brought from #38.

**Comment by licaon-kter** [comment]
https://developer.android.com/guide/topics/resources/multilingual-support.html

**Comment by XyLoNaMiyX** [comment]
>  A device is set to es_MX […] the system would load strings from the default (en_US) resource file, even if the app has Spanish resources localized under es_ES.

They couldn't just trim the `_ES` part from the available locale in the application resources…

> why you should store French strings in fr rather than fr_FR for Android 7.0 or higher.

I think most people does this already, and I've never seen the `values-b+es+419` notation… It doesn't say how the system *resolves* the resources, because Stringlate wouldn't be able to handle the `values-b+en+001` notation anyway.

**Comment by XyLoNaMiyX** [comment]
I think a solution could be to **ensure** that `.getCountry()` is empty, so it selects the "bare" one.

**Comment by licaon-kter** [comment]
https://developer.android.com/reference/java/util/Locale.html#getDisplayCountry%28java.util.Locale%29

**Comment by XyLoNaMiyX** [comment]
> https://developer.android.com/reference/java/util/Locale.html#getDisplayCountry%28java.util.Locale%29

Not necessary thanks, ensuring that `.getCountry().isEmpty()` does the trick and selects the right one :)
