### ISSUE TITLE
Add support for html files.

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#63]
This app currently fails when trying to load html files ( I've tried for https://github.com/klausw/hackerskeyboard )

**Comment by XyLoNaMiyX** [comment]
Fails in which way? I've seen it has multiple files with `<string` (I don't know why people call those files things like `donottranslate` instead setting `translatable="false"`…) so it probably loads a random file. Multiple files are not yet supported but it's planned. Is that your problem?

**Comment by OffifialMITX** [comment]
Oh, sorry, I've forgot to mention, it says "no string.xml files were found" which is basicly not an error, I guess.

Anyway, I can't use it this way, can't it be expanded to any file type when Stringlate finally edits the files instead of recreating them (or is it already the case?)?

Am 6. Januar 2017 15:18:14 MEZ, schrieb Lonami <notifications@github.com>:
>Fails in which way? I've seen it has multiple files with `<string` (I
>don't know why people call those files things like `donottranslate`
>instead setting `translatable="false"`…) so it probably loads a random
>file. Multiple files are not yet supported but it's planned. Is that
>your problem?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/63#issuecomment-270911413

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
> it says "no string.xml files were found"

It does work on the current upstream version, so don't worry. GitHub, for some reason, limited the results when searching for the files to 30 (and the repository you mentioned has more, thus some are missing). Now I clone the whole repository, so I don't have this issue.

> can't it be expanded to any file type when Stringlate finally edits the files instead of recreating them

Could you explain this a bit better?

**Comment by OffifialMITX** [comment]
My fault, I forgot that #21 is already solved.

**Comment by XyLoNaMiyX** [comment]
I was gonna "bump" or something for you to provide some more feedback on this haha! Should we close this issue then?

**Comment by OffifialMITX** [comment]
I've answered a long time ago via E-Mail but seems like it haven't been sent it :-{

**Comment by XyLoNaMiyX** [comment]
That's okay :)
