### ISSUE TITLE
Graphics problem when selecting text in the main menu

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#64]
The app starts to ignore the status bar, I had the problem when I selected the Link for #63 .

**Comment by XyLoNaMiyX** [comment]
It happens with long links, and I have no idea why it does such thing. I used the default template provided by Android Studio so I don't know why this happens!

**Comment by XyLoNaMiyX** [comment]
For further reference and in case anyone has idea…
![reasuh](https://cloud.githubusercontent.com/assets/6297805/21720642/98edfc5a-d424-11e6-8356-0f888431f203.png)

**Comment by OffifialMITX** [comment]
The same thing happens if you manually type at least 34 characters/digits, hopefully its a useful information, took me 40 seconds to find out ;-)

Am 6. Januar 2017 15:27:28 MEZ, schrieb Lonami <notifications@github.com>:
>For further reference and in case anyone has idea…
>![reasuh](https://cloud.githubusercontent.com/assets/6297805/21720642/98edfc5a-d424-11e6-8356-0f888431f203.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/64#issuecomment-270913261

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by licaon-kter** [comment]
Saw this too on NDP4, waited to confirm on LL or MM.

**Comment by XyLoNaMiyX** [comment]
> The same thing happens if you manually type at least 34 characters/digits

Yes it doesn't matter whether it's an URL or not; the length of the string is the only thing that matters.

**Comment by OffifialMITX** [comment]
I've noticed that nothing like that happens with the 2 lines above, what's actually the diffirence between them?

**Comment by XyLoNaMiyX** [comment]
> what's actually the diffirence between them?

The first is inside a `<LinearLayout>`, the second isn't.

**Comment by OffifialMITX** [comment]
I meant the difference between the *first and second* **and** the *third* one, or is that's what you're talking about?

I don't know much about programming so that's why I wonder if you couldn't just put like a part of the code from the first into the third line.

Am 15. Januar 2017 17:44:32 MEZ, schrieb Lonami <notifications@github.com>:
>> what's actually the diffirence between them?
>
>The first is inside a `<LinearLayout>`, the second isn't.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/64#issuecomment-272707003

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
> I meant the difference between the *first and second* **and** the *third* one, or is that's what you're talking about?

Yes, that's what I meant, the first *two* fields are inside a `<LinearLayout>`, and the second is not. Anyway; I tried making them both be "under the same conditions", and no, it neither worked, nor was an elegant solution.

> I don't know much about programming

Sorry, I really told you the *exact* difference ;-)

**Comment by OffifialMITX** [comment]
I know only some HTML so I had the feeling that linear layout is like a **TABLE** where is only one cell per line but nevermind then.

Am 15. Januar 2017 18:03:45 MEZ, schrieb Lonami <notifications@github.com>:
>> I meant the difference between the *first and second* **and** the
>*third* one, or is that's what you're talking about?
>
>Yes, that's what I meant, the first *two* fields are inside a
>`<LinearLayout>`, and the second is not. Anyway; I tried making them
>both be "under the same conditions", and no, it neither worked, nor was
>an elegant solution.
>
>> I don't know much about programming
>
>Sorry, I really told you the *exact* difference ;-)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/64#issuecomment-272708291

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
> so I had the feeling that linear layout is like a **TABLE** where is only one cell per line but nevermind then.

Yeah it's kinda like that, `<LinearLayout>` can act like a single-row-table or a single-column-table.

**Comment by OffifialMITX** [comment]
I'd have an idea for an UI improvement which I will upload soon.

**Comment by OffifialMITX** [comment]
May I have also a screenshot of the main screen?

**Comment by XyLoNaMiyX** [comment]
> May I have also a screenshot of the main screen?

Do you mean the _Add new repository_ screen?

**Comment by OffifialMITX** [comment]
Yes, thank you.

**Comment by XyLoNaMiyX** [comment]
[`d6d2cac`](https://github.com/LonamiWebs/Stringlate/commit/d6d2cacfd8fa3e67ff02a36c42f4d7d36b3c4d14).
