### ISSUE TITLE
Don't ping Google

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#69]
Change [this](https://github.com/LonamiWebs/Stringlate/blob/848cbac73f3cb2187eb5e0c71edc483d59f79c7c/src/app/src/main/java/io/github/lonamiwebs/stringlate/git/GitHub.java#L46) to [something else](https://stackoverflow.com/questions/36268948/how-to-check-internet-available-in-android/36269030#36269030) as Android already has mechanisms to detect if the internet is connected.

The funny thing is if I block that, it will fail, then if I restart the app it will work anyway.

**Comment by XyLoNaMiyX** [comment]
Being connected doesn't usually imply having internet. But I agree pinging sucks because in some connections it takes several seconds although I have access (just a lot of packet missed).

Although this method requires another permission, it shouldn't scare anyone.

**Comment by XyLoNaMiyX** [comment]
[Done](https://github.com/LonamiWebs/Stringlate/commit/6f98263b2dee1b9ddd4049d139484f5fba94f925).
