### ISSUE TITLE
Remove top 50

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#7]
Or make it better, now it mean "first 50 by name" which is not that useful.

**Comment by XyLoNaMiyX** [comment]
> Or make it better

What do you suggest? Any nicer way to put it? If there is no "limit", then it will show all the over-a-thousand applications on F-Droid, which is kind of crazy.

**Comment by licaon-kter** [comment]
The number of items might be an issue on some (old/slow) devices indeed.
You can help by having a "show app icons" option, that is OFF by default (and it helps with bandwidth too).
Else you have search already, having it limited to 50 is strange, even I had the impression that only those were available.

**Comment by Lin-Buo-Ren** [comment]
My first impression of "Show only top 50" is the 50 most popular ones, it's indeed pretty meaning less just to show the first 50 apps from the top of the list.

It should be based on popularity or other factors, translator should be more interested on apps that has many users or are in trend.

**Comment by XyLoNaMiyX** [comment]
> […] on apps that has bigger userbase or are in trend.

F-Droid has no way to tell how many downloads an application has. I had thought on adding a "Sort by…" menu option, which allowed to sort in ascendant/descendant order by upload date, by name… But that seemed like adding too many options. I think leaving only the search and always showing all the applications should be enough (also allowing "fast scroll").

**Comment by Lin-Buo-Ren** [comment]
Or maybe categorize using the application category, just like in F-droid?

**Comment by XyLoNaMiyX** [comment]
Or maybe even random order since it's to "discover new things", not something you've already seen!

I would like to keep it simpler than adding a category selector. If you know an application, you can look it up. If you don't, you can just scroll without discriminating by category.

**Comment by licaon-kter** [comment]
It does not matter how you do it, just add a "Load more..." at the end so you signal that there are more.

**Comment by XyLoNaMiyX** [comment]
> just add a "Load more..."

I liked that idea. Might do that, but after `v0.9.2` is released. Thanks for the ideas.

**Comment by OffifialMITX** [comment]
> F-Droid has no way to tell how many downloads an application has.

It will, the coming version 0.103 is going to have major UI/UX improvements, also providing things like rating and statistics

**Comment by XyLoNaMiyX** [comment]
> It will, the coming version 0.103 is going to have major UI/UX improvements, also providing things like rating and statistics

That's amazing news! Let's hope it's as easy to use as before so so the *Discover* activity doesn't break too much…

**Comment by OffifialMITX** [comment]
> That's amazing news!

I think that too, you can <a href="https://gitlab.com/fdroid/fdroidclient/milestones/20">get more information</a>, if you want to.

Maybe discovering new apps would be easier if you could "share" apps to Stringlate.(?)

Am 20. Dezember 2016 16:10:04 MEZ, schrieb Lonami <notifications@github.com>:
>> It will, the coming version 0.103 is going to have major UI/UX
>improvements, also providing things like rating and statistics
>
>That's amazing news! Let's hope it's as easy to use as before so so the
>*Discover* activity doesn't break too much…
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/7#issuecomment-268267053

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
Thanks for the link, it's exciting!

> Maybe discovering new apps would be easier if you could "share" apps to Stringlate.(?)

You can already open https://github.com/owner/repo/ links via Stringlate directly (it needs to ending slash). I think that also by sharing it's unnecessary: you can as well copy the URL directly.

**Comment by OffifialMITX** [comment]
I have an idea, maybe Stringlate coukd search for applications from F-Droid on the device and show the ones which aren't translated fully in a special list, e.g. "Apps on the phone" since you actually want translate apps you're using most frequently anyway.

Besides, I don't like the implementation of the compass symbol since for me it looks like a button for itself. Please either remove it or add e.g. a <b>+</b> to the other button.

**Comment by XyLoNaMiyX** [comment]
> and show the ones which aren't translated fully in a special list, […]

This involves scanning the whole repository for *all* the applications. Probably not something I can afford since the GitHub API calls are "anonymous" (you're not logged in).

However, I did think to make it an `ExpandableList`, in such a way that, after clicking an item, it would show options such as "Scan", "Add". Scanning would also tell you things like "This application is not translated to your current locale."

> since you actually want translate apps you're using most frequently anyway.

You can already search the application you wish to translate though!

> Please either remove it or add e.g. a + to the other button.

The later option is a better choice. By the way, I also wanted to add another icon for the "Save" button, but it looks a bit odd. Should the "Add" icon be on the left side, or on the right side? Probably left, hopefully one won't mistake it with the other button.

**Comment by OffifialMITX** [comment]
> Should the "Add" icon be on the left side, or on the right side?

I've also thought of the right side first but that's just not what material design is thought to. Maybe that would make the orritation even bigger. (Not sure if that's the correct expression)

You know what's the main difference between a user and a programmer? Users are lazy. That's why they don't learn any programming language. And that's why they probably don't want to search for the app's name. Why search for it? Because they always look at the icon, again, because they are too lazy to read the name every time, and slowly forget them.

"Programming today is a race between software engeneers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning" - Rich Cook

Am 21. Dezember 2016 22:58:58 MEZ, schrieb Lonami <notifications@github.com>:
>> and show the ones which aren't translated fully in a special list,
>[…]
>
>This involves scanning the whole repository for *all* the applications.
>Probably not something I can afford since the GitHub API calls are
>"anonymous" (you're not logged in).
>
>However, I did think to make it an `ExpandableList`, in such a way
>that, after clicking an item, it would show options such as "Scan",
>"Add". Scanning would also tell you things like "This application is
>not translated to your current locale."
>
>> since you actually want translate apps you're using most frequently
>anyway.
>
>You can already search the application you wish to translate though!
>
>> Please either remove it or add e.g. a + to the other button.
>
>The later option is a better choice. By the way, I also wanted to add
>another icon for the "Save" button, but it looks a bit odd. Should the
>"Add" icon be on the left side, or on the right side? Probably left,
>hopefully one won't mistake it with the other button.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/7#issuecomment-268652369

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
No offence, but neither all users are lazy nor all programmers are not. The icon is already shown on the discover activity so users can also look for that. It's not hard to make the installed apps show up first, but I don't really think it's necessary.

Installed apps sorted alphabetically and then a jump to non-installed? I don't see it. Not until the idea gets more support anyway.

**Comment by OffifialMITX** [comment]
Well, maybe my expression was too linear, I didn't mean that every user os automatically lazy and so on. I just described a worst-case user.

Am 21. Dezember 2016 23:41:47 MEZ, schrieb Lonami <notifications@github.com>:
>No offence, but neither all users are lazy nor all programmers are not.
>The icon is already shown on the discover activity so users can also
>look for that. It's not hard to make the installed apps show up first,
>but I don't really think it's necessary.
>
>Installed apps sorted alphabetically and then a jump to non-installed?
>I don't see it. Not until the idea gets more support anyway.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/7#issuecomment-268662917

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by licaon-kter** [comment]
> Installed apps sorted alphabetically and then a jump to non-installed? 

Sounds interesting. I get this, feels out of place when you open an app and it's not translated, having them first gives you a little boost: "hey you're using that, how about adding a translation?"

**Comment by XyLoNaMiyX** [comment]
How would you show the difference between installed and not installed to the user? Different background? A label on top? An icon on the top-right corner of each application?

**Comment by OffifialMITX** [comment]
Perheaps not just jump but highlight with a "V"?

Am 21. Dezember 2016 23:46:10 MEZ, schrieb licaon-kter <notifications@github.com>:
>> Installed apps sorted alphabetically and then a jump to
>non-installed? 
>
>Sounds interesting. I get this, feels out of place when you open an app
>and it's not translated, having them first gives you a little boost:
>"hey you're using that, how about adding a translation?"
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/7#issuecomment-268663783

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
A "V"? What did you mean?

**Comment by OffifialMITX** [comment]
I mean like in a checklist, I just don't get the right word. Hoes maybe?

Am 21. Dezember 2016 23:51:42 MEZ, schrieb Lonami <notifications@github.com>:
>A "V"? What did you mean?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/7#issuecomment-268664897

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by licaon-kter** [comment]
A symbol is nice, having them listed first feels way better though.

**Comment by XyLoNaMiyX** [comment]
Tick? ✔️✅

**Comment by OffifialMITX** [comment]
Yes, that's what I meant.

Am 21. Dezember 2016 23:57:34 MEZ, schrieb Lonami <notifications@github.com>:
>Tick? ✔️✅
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/7#issuecomment-268665933

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
Added on [commit#5d2eba](https://github.com/LonamiWebs/Stringlate/commit/5d2eba88663a0844bc76db0ae06716279209a90a).

**Comment by OffifialMITX** [comment]
Cool!

Am 22. Dezember 2016 10:44:58 MEZ, schrieb Lonami <notifications@github.com>:
>Added on
>[commit#5d2eba](https://github.com/LonamiWebs/Stringlate/commit/5d2eba88663a0844bc76db0ae06716279209a90a).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LonamiWebs/Stringlate/issues/7#issuecomment-268760442

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
> You can help by having a "show app icons" option, that is OFF by default

Added on [commit#ac45fc](https://github.com/LonamiWebs/Stringlate/commit/ac45fc41c49598cf51642079d42aad81a76208e4). Note that icons which are already saved will still be shown (can be fixed by first clearing the cache).

**Comment by OffifialMITX** [comment]
I've got two ideas!

Either you could add a new tab on the right and remove the "search for repos" button,

<b>or</b>

Just remove the "search" button and let the "add" button do the same thing if the forms are empty.

And besides, please change the color of the buttons, it's not a good idea to have yellow text on white background. Maybe you can change the button's background to <b>#A0A0A0</b> or so?

**Comment by XyLoNaMiyX** [comment]
> Either you could add a new tab on the right and remove the "search for repos" button

No, I hate fragments. Also, how would it show to sync the repository? The menu would have to change, which *can* do, but I think it's unnecessary (indeed, it was going to be like that, but then realized the menu problem).

> Just remove the "search" button and let the "add" button do the same thing if the forms are empty.

That would be a bit confusing. Why would the *add* button open the *discover* activity? What if the user chose a repository, but changed their minds and wanted to choose another? They would have to manually clear the fields.

> it's not a good idea to have yellow text on white background.

It's not a light yellow. Also, I didn't choose to use that color for the text, Android just took the accent color for it by default. I find it readable enough though.
