### ISSUE TITLE
Language region code

### ISSUE THREAD

**Issue by Cj-Malone** [LonamiWebs/Stringlate#70]
I have en-rGB as in real English, but it still shows up as the code in the "Selected locale" list. The same happens with zh-rTW in this project.

**Comment by licaon-kter** [comment]
#58 related?

**Comment by XyLoNaMiyX** [comment]
> #58 related?

Yes, it's been fixed [here](https://github.com/LonamiWebs/Stringlate/commit/1535c397906b394efa837d8d62a98a12d11a27b1#diff-b8864b781ec63f3e54d6eed5e073261dR38). This will be working on the next release.
