### ISSUE TITLE
UI redisigns

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#71]
I've opened this referring to #12 and #64 to keep everything clear because after some work I have plenty of images which I will spam this issue with.

**Comment by OffifialMITX** [comment]
Here are some basic ideas how the progress could look in the icon.
I do know that not every icon is a circle, I'm working on ideas how this could be solved, the last two should work with every icon.
<table><tr><td>
<img height="150" alt="icon" src="https://cloud.githubusercontent.com/assets/22666602/21978815/88670d1c-dbdc-11e6-9e27-b112cebbef10.png">
</td><td>
<img height="150"  alt="icon" src="https://cloud.githubusercontent.com/assets/22666602/21978819/8d70f214-dbdc-11e6-99b2-973bffac44ca.png">
</td><td>
<img height="150"  alt="icon" src="https://cloud.githubusercontent.com/assets/22666602/21978823/93eef46a-dbdc-11e6-8631-ba9bca8ca162.png">
</td><td>
<img height="150" src="https://cloud.githubusercontent.com/assets/22666602/21978829/9ad96e4a-dbdc-11e6-87a0-a4fdfc23c35b.png">
</td><td>
<img height="150" alt="icon"  src="https://cloud.githubusercontent.com/assets/22666602/21978836/a39ec57a-dbdc-11e6-9ff8-01fb204c35e4.png">
</td><td>
<img height="150" alt="icon"  src="https://cloud.githubusercontent.com/assets/22666602/21978843/ab300178-dbdc-11e6-9a78-22fdbe3b590d.png">
</td></tr>
<tr><td>
<img height="150" alt="icon"  src="https://cloud.githubusercontent.com/assets/22666602/21978850/b19f5478-dbdc-11e6-908b-8622ad934b02.png">
</td><td>
<img height="150"  alt="icon" src="https://cloud.githubusercontent.com/assets/22666602/21978852/b715f038-dbdc-11e6-998a-e4e4d097d85b.png">
</td><td>
<img height="150"  alt="icon" src="https://cloud.githubusercontent.com/assets/22666602/21978859/bf8cfa90-dbdc-11e6-820c-001c37903522.png">
</td><td>
<img height="150"  alt="icon" src="https://cloud.githubusercontent.com/assets/22666602/21978862/c6d0c480-dbdc-11e6-864d-ab2df9867919.png">
</td><td>
<img height="150"  alt="icon" src="https://cloud.githubusercontent.com/assets/22666602/21978869/cd2b9116-dbdc-11e6-9143-3ac216e0365a.png">
</td><td></td></tr>/table

**Comment by OffifialMITX** [comment]
this is how it could look in the list of recent apps:
<img height="800" src="https://cloud.githubusercontent.com/assets/22666602/21979613/fd4ce0fe-dbdf-11e6-9902-e14d04642d6d.png">

**Comment by OffifialMITX** [comment]
Here are some start menu UI ideas:

I used the colored Stringlate icons to represent other apps.

<img alt="possible UI" width="350" src="https://cloud.githubusercontent.com/assets/22666602/21979772/bb6ea5b8-dbe0-11e6-9106-87b667ab8ae8.png">
<img alt="possible UI" width="350" src="https://cloud.githubusercontent.com/assets/22666602/21979781/c4aea3c6-dbe0-11e6-98f6-68363b91ce2c.png">
<img alt="possible UI" width="350" src="https://cloud.githubusercontent.com/assets/22666602/21979792/cf6cc3d8-dbe0-11e6-855f-9aaa30b8ae40.png">
<img alt="possible UI" width="350" src="https://cloud.githubusercontent.com/assets/22666602/21979811/e08a3038-dbe0-11e6-8481-3c4dd753ee39.png">

My favorite is the second one.

**Comment by OffifialMITX** [comment]
That's it for now.

**Comment by XyLoNaMiyX** [comment]
I liked this the most:
<img height="150" src="https://cloud.githubusercontent.com/assets/22666602/21978829/9ad96e4a-dbdc-11e6-87a0-a4fdfc23c35b.png">

> the last two should work with every icon.

Sadly, they're a bit "aggresive" in my opinion.

> this is how it could look in the list of recent apps:

I think the progress bar could be a bit thicker?

> I used the colored Stringlate icons to represent other apps.
> <img height="320" src="https://cloud.githubusercontent.com/assets/22666602/21979772/bb6ea5b8-dbe0-11e6-9106-87b667ab8ae8.png">

Note that although every application should have an icon, _this might not be the case_, even more if you're upgrading because none of the added repositories will have an icon. Also, I would like to still see the name. But maybe the icon as main part would look good. And after all, the icon could be made up from the first letter of the filename in white + some background color.

> I think it's useful if you have one line where you can type either Owner/Repo or the URL.

Yes.

> <img height="320" src="https://cloud.githubusercontent.com/assets/22666602/21979792/cf6cc3d8-dbe0-11e6-855f-9aaa30b8ae40.png">

Out of those 3 carousels, this is the one I like the most. But let's not forget that I'm probably the one who has to implement this, and that doesn't seem trivial :P 

Thanks for putting all this effort although I discared most options 😳.

**Comment by Lonami** [comment]
@OffifialMITX any update on this, or do you like the application now with that bottom navigation bar?

**Comment by OffifialMITX** [comment]
I'm not very sure, I mean, id __does__ look better thanbit did before, but I just have the feeling that it doesn't really fit, although I can't tell why. Anyways, it looks fine, and you can leave it the way it is for as long as you don't have the time to completely rebuild the design.

Btw, this is of course only _my_ opinion, I don't say you __have__ to do anything if __you__ think it doesn't fit for any reason.

**Comment by Lonami** [comment]
I feel like the UI has changed quite a bit so I don't find this issue relevant anymore. Don't hesitate to add new comments or even open a new more fresh issue than this one. I'm just cleaning up :)
