### ISSUE TITLE
2nd (or more) item of string-array not being saved

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#77]
I tried to translate Taskbar but after I was ready, I couldn't upload it (issue/gist) or esport (SD).

After I returned to retry uploading it, some of the strings weren't translated.

I saved the file and returned, and the strings were missing again.

After I took a closer look I noticed that every of those non-translatable strings contains a **:** in its name so I suppose this is the problem.

**Comment by XyLoNaMiyX** [comment]
> I noticed that every of those non-translatable strings contains a : in its name so I suppose this is the problem.

The `:` actually is an indicator for the index of the item in the array of strings you're trying to translate. So the problem pops up when trying to add new strings to the arrays (or plurals). I'll look into it.
