### ISSUE TITLE
Fails to upload a gist

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#79]
I thought it was because of #77 but now I translated Stringlate's new strings and can't upload it either.

**EDIT:** Every time I try to, I'm being instantly sent back to the translation screen.

**Comment by XyLoNaMiyX** [comment]
I fixed this on [`0b77ad3`](https://github.com/LonamiWebs/Stringlate/commit/0b77ad3e7458e4457a437346354889ab542e2b74), I probably release a quick patch because this is an important bug.
