### ISSUE TITLE
Don't allow translating repositories containing "Transifex" on their README.md

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Stringlate#80]
Perhaps this is a bit aggressive. Maybe a warning should be shown instead. The idea is to sneak into the `README.md` and scan for `"Transifex"`, `"Crowdin"` or `"Weblate"` strings in it. If the `README.md` contains any of these, chances are they use those online platforms.

**Comment by licaon-kter** [comment]
I'll say [again](https://github.com/LonamiWebs/Stringlate/issues/52#issuecomment-269523028):

> Regarding external translations sites, I see that even when those exist there are users that choose to translate strings.xml directly, say to see how the git/github workflow works or find it easier like that. And devs will use those translation, and rightly so, that work is useful.

Also:
* those sites *need* you to be online to be used
* and sometimes even offer the posibility to save a strings.xml, edit it on you device and then reupload it

So, yeah, maybe add a `Notice` (not Warning) but don't hamper anything.
If the work is done, site or app, use it.

**Comment by XyLoNaMiyX** [comment]
> So, yeah, maybe add a `Notice` (not Warning) but don't hamper anything.

Any idea on what it could say? Maybe something like "*Note: This repository might use a external site for managing translations…*"?

**Comment by licaon-kter** [comment]
Not sure on the wording, this still sounds like _"...and that will somehow make translation transfer harder"_

**Comment by XyLoNaMiyX** [comment]
> I'll say [again](https://github.com/LonamiWebs/Stringlate/issues/52#issuecomment-269523028)

By the way, I know that, but I also know some people is more strict with it, so that's why I opened this. I don't want a newcomer to suddenly find they've translated a really large application and it can't be of any use, or little, or somewhat a more cumbersome process. You know?

> Not sure on the wording

Let's see if anyone else can give more ideas on how this could (and if it should) be done.

**Comment by licaon-kter** [comment]
Strict, maybe, but it's just a matter of `merge-new-from-user, push-to-translation-site, done`

**Comment by Jibec** [comment]
If a translation platform exists, it means it's handling the translation process and translator would expect to see changes inside it. I would suggest not to let the user translate it in Stringlate without inviting the user to use dedicated, despite the fact I like Stringlate's concept very much, it forks the production tool of the translator community.

I would be more optimistic in the message: "We are happy to tell you we think there a dedicated translation platform is used for this tool ! Please try to find this project in 'Weblate/Zanata/Pootle/Transifex/Crowdin to make sure you get the best translation experience. You can still use Stringlate, but depending on their processes, the upstream community may ask you to go through the platform."

**Comment by XyLoNaMiyX** [comment]
Hmm, maybe we should just show that kind of hint, like using an information icon and say: _"This application might use an external site to manage the translations. You should be able to use Stringlate to later export the `.xml` file and import it on those sites if any…"_. My wording is long, confusing and not really good… But that idea is still better than no notice at all.

**Comment by BoFFire** [comment]
I like the idea of Crowdin and Weblate.
Hope see it on Stringlate :)
Thanks you for all :)

**Comment by Lonami** [comment]
Commit message was too long to add "closes blah blah". I added such notice on commit [`3922b89`](https://github.com/LonamiWebs/Stringlate/commit/3922b893546cc01a080e2c5bb2848e16967e18bb). Transifex, Crowdin, Wweblate, Zanata and Pootle are now recognised.

**Comment by Poussinou** [comment]
@Lonami Maybe you can add [OneSky](https://www.oneskyapp.com/) and [POEditor](https://poeditor.com/) as well? Some Android applications are translated via this services, like [StreetComplete](https://github.com/westnordost/StreetComplete/) or [Shadowsocks](https://github.com/shadowsocks/shadowsocks-android)

**Comment by gsantner** [comment]
how to detect these? i cannot find an special config file in repo for these services

**Comment by Lonami** [comment]
Just two more strings here should do the trick @gsantner :P
