### ISSUE TITLE
Don't reset current string position on enabling "show translated strings"

### ISSUE THREAD

**Issue by licaon-kter** [LonamiWebs/Stringlate#81]

**Comment by XyLoNaMiyX** [comment]
Expected behaviour the other way round? i.e. you have selected a string which _is_ translated and you disable "Show translated"?

**Comment by licaon-kter** [comment]
Show the next untranslated.

**Comment by XyLoNaMiyX** [comment]
> Show the next untranslated.

And if that's not possible, the previously non-translated string will be shown. If not even that is possible, do nothing.

**Comment by licaon-kter** [comment]
> And if that's not possible

They're all translated then I guess...

**Comment by XyLoNaMiyX** [comment]
> They're all translated then I guess...

No, imagine the following case where:
- `T` means translated.
- `N` means **not** translated.
- `X` means "here" (and it **is** translated, so it's not a candidate to be selected).

```
NNNTNTXTT
    ^
// That one should be selected.
```

**Comment by licaon-kter** [comment]
Oh, wrong quote, I meant:

> If not even that is possible, do nothing.
