### ISSUE TITLE
Added ru (Russian) translation

### ISSUE THREAD

**Issue by ashed** [LonamiWebs/Stringlate#86]
I have translated your application into `ru` (*Russian*). Here is the xml:
```xml

```

---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by XyLoNaMiyX** [comment]
#79. F-Droid needs to update, and I don't know when it will be :(

Sorry for the inconveniences and please, do not "export" your translations until you get an update. They won't work.

**Comment by XyLoNaMiyX** [comment]
(Translation given via a different channel, thank you).
