### ISSUE TITLE
Progress is lost when switching to Stringlate via Taskbar

### ISSUE THREAD

**Issue by OffifialMITX** [LonamiWebs/Stringlate#87]
Stringlate loses all unsaved content if being switched from an other app / the launcher via [Taskbar](https://github.com/farmerbb/Taskbar).

**Comment by OffifialMITX** [comment]
Maybe its the same thing that happened while screen rotation so maybe after you fix this one we'll be able to rotate again!

**Comment by XyLoNaMiyX** [comment]
Maybe I should just save the strings automatically rather than having a button. I mean, I could keep the save button, but I don't know if anyone would, for any reason, want to lose their progress. What do you think @OffifialMITX?

**Comment by OffifialMITX** [comment]
Good idea, maybe you should keep the last edited open.

I just wonder when exactly it should be saved. After clicking next? Wouldn't solve the problem I had. After every charachter? Too often maybe. Every time you press space?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
> I just wonder when exactly it should be saved.

When the activity is paused (i.e., when you "leave" it).

> After clicking next?

If it was saved when "Next" is clicked, then #23 would make no sense.

> After every charachter? Too often maybe.

Yep, too often.

> Every time you press space?

AFAIK, every language/idiom/whatever you call it uses the space to separate words. But it doesn't seem like a too good idea, I will just do the pause way. If you'd like to know more about when pause would be called:
[![Activity lifecycle](https://developer.android.com/guide/components/images/activity_lifecycle.png)](https://developer.android.com/guide/components/activities/activity-lifecycle.html)

**Comment by OffifialMITX** [comment]
Well, yes, #23 wouldn't make any sence anymore, just like the [SAVE] button, but do we really need it?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by XyLoNaMiyX** [comment]
> but do we really need it?

Really really *really*, no, we don't. Does it look good? Yes, it does. In my opinion some people will find it "safer" to click the save button manually rather than depending on an automatic process, although they both do the same.

But yeah, it could potentially be removed if more people gave more reasons.

**Comment by licaon-kter** [comment]
Remove it!

**Comment by XyLoNaMiyX** [comment]
> Remove it!

What do you suggest to do with the "*strings.xml file saved successfully*" toast? What if it fails, but since it's automatic the user can't click on "Save" manually?

**Comment by licaon-kter** [comment]
Why would it fail? If it does then ask the user for... something.

**Comment by XyLoNaMiyX** [comment]
> Why would it fail?

No idea, it just can. Now chances are so small it would do no harm if we removed it I guess… I just don't know. How would we ask the user? Right now they can just click "Save" again until it actually works. But if for some reason it fails, and I enter a loop until it does success, then maybe it becomes an infinite loop (this is, if we removed the save button).

**Comment by licaon-kter** [comment]
Popup a dialogue `Retry/Cancel`

If it fails by missing permissions, do ask them again.

Anyway, if it fails things went strange already.

**Comment by XyLoNaMiyX** [comment]
> Remove it!

Do you want to conserve #23 in any other way?

**Comment by licaon-kter** [comment]
No,  #23 is useless now.

**Comment by OffifialMITX** [comment]
What about an ending screen where after typing anything in the last string a button called finish in the middle appears which opens a menu with the title "Congratulations! You translated all strings of %s! You now can:" and a list of all export functions?

**Comment by XyLoNaMiyX** [comment]
Hm… I don't think it's necessary, they have the menu with two taps. *Perhaps* on that same screen, "All strings are translated.", and below all the available buttons to export. But I don't think it's necessary.
