### ISSUE TITLE
Cannot pull new strings

### ISSUE THREAD

**Issue by BoFFire** [LonamiWebs/Stringlate#89]
Hi,
Here are some stringlated strings of Stringlate in arabic :
https://gist.github.com/BoFFire/c1cdc9be648460cae623590668691a72

**Comment by XyLoNaMiyX** [comment]
Nice, thank you.

**Comment by XyLoNaMiyX** [comment]
Uhm sorry. A lot of strings are missing. Have you tried synchronizing the repository before starting the translation? There are over 160 strings, but your gist doesn't even have half of those. Would you mind adding the strings left? If not, I will still merge this :)

**Comment by BoFFire** [comment]
Hi, yep I Think so and was surprises that non translated strings were not added.
May be I've made a mistake. I'll recheck.
Thanks you for the fast answer.

**Comment by BoFFire** [comment]
Got the same in test2 o_O
https://gist.github.com/BoFFire/e415d1a287be7d0813036cde3674750c

**Comment by XyLoNaMiyX** [comment]
Hmm. If you hit the "Update strings.xml" button, namely this:
![sync](https://github.com/LonamiWebs/Stringlate/raw/master/src/app/src/main/res/drawable-xxxhdpi/ic_sync_black_24dp.png)

It doesn't work?

**Comment by BoFFire** [comment]
Yep, got the same strings on SD too.

**Comment by XyLoNaMiyX** [comment]
Very strange behaviour. "![sync](https://github.com/LonamiWebs/Stringlate/raw/master/src/app/src/main/res/drawable-mdpi/ic_sync_black_24dp.png) Update strings.xml" should pull the latest changes. What Stringlate version are you using? Have you tried exiting and entering the application after syncing again?

**Comment by BoFFire** [comment]
I'm using the version 0.9.9 of Stringlate but the arabic language is created for the first time. I'm trying to reproduce the issue by creating a New language :)

**Comment by BoFFire** [comment]
Issue reproduced when I tried to create a New language for br (breton). When saved I Got only the translated strings event with sync.

**Comment by XyLoNaMiyX** [comment]
> but the arabic language is created for the first time.

I tried creating a new language too on my own testing repository, and it pulled new strings correctly. I'm using the upstream version, not `v0.9.9`, but I can't remember having modified any code related to pulling new strings so it should work the same. Do the rest of languages export everything correctly? How many locales are shown?

**Comment by BoFFire** [comment]
By default and for Stringlate app I have 10 languages shown excluding arabic and any other testing language.

**Comment by XyLoNaMiyX** [comment]
I can't reproduce the bug @BoFFire :(

Check the following YouTube video where I use https://github.com/LonamiWebs/Strest to try to reproduce the bug. It would be great if you could try out with some repository of yours, pushing new strings, and telling me if you can pull the changes. It's very, very strange that it doesn't pull new strings…

<a href="https://youtu.be/iVVz-IzsWpI" target="_blank"><img src="http://img.youtube.com/vi/iVVz-IzsWpI/0.jpg" 
alt="Bug" width="480" height="360" border="10" /></a>

@licaon-kter I would also like if you could please give this strange bug a go? You have never had issues with this either… I'm clueless.

**Comment by licaon-kter** [comment]
New locale says 156 strings... Not sure what or how to test.


@XyLoNaMiyX By the way, reading the posts again did you see the remark that @BoFFire said: `I...was surprised that non translated strings were not added` ? 

That is correct, untranslated strings are not added (they're pulled from the main strings of the default language), maybe it's all a misunderstanding?

**Comment by XyLoNaMiyX** [comment]
> New locale says 156 strings.

Same as mine. If you've previously synced Stringlate's strings then it has to work.

> Not sure what or how to test.

Nothing I guess since you've been able to pull new strings from Stringlate.

> did you see the remark that @BoFFire said: _I...was surprised that non translated strings were not added_? […]

I didn't quite unterstood it but now do. Yes, "non translated" are not pulled *unless* the repository got the strings via someone else in the meantime. Which is not the case.

But, if pulling **works**, he *should* be able to have more strings available for him to translate. Which I assumed was the issue since he couldn't continue/not all are shown for him to translate, thus when exporting, only a few were exported (because he couldn't translate more).

**Comment by XyLoNaMiyX** [comment]
@BoFFire, what number shows on the bottom line of the translation activity? Something like "X/Y strings translated". What does the `Y` says?

**Comment by licaon-kter** [comment]
What does X say too?

**Comment by BoFFire** [comment]
Hi,
I would like to precise that some translators like me, proceed to translated 1 string sometimes and hundred of strings other times depending on the available time and you know this :).
I did translated may be 15% of Stringlate string when I was in the café. I can do more translations if I could synch again to get the (ar) translated + the original Strings.
Is there any misunderstanding of the issue ? :-)
Thank you again.

**Comment by licaon-kter** [comment]
Then yes, read my post above. the exported file contains ONLY the translated strings.

**Comment by XyLoNaMiyX** [comment]
> Is there any misunderstanding of the issue ? 

Big one indeed. I'm glad this "strange issue" doesn't really exist.

> the exported file contains ONLY the translated strings.

It would be great if it automagically exported the missing strings in the translated locale, right? ;)

Not sure if I should close this issue and let you open another @BoFFire after you have all the strings translated. I will wait until then, there is no need to rush. Thanks again.

**Comment by BoFFire** [comment]
Issue closed, happy Stringlating :-)
