### ISSUE TITLE
updated german translation

### ISSUE THREAD

**Issue by joergister** [LonamiWebs/Stringlate#91]
You can find the xml- file using this link 
https://gist.github.com/a061b76a06a3edf545d89441ba8bb7ea
By the way, great APP!!! Really useful.

**Comment by XyLoNaMiyX** [comment]
Thanks for the translation and feedback! Will add it tomorrow.

**Comment by XyLoNaMiyX** [comment]
I've had this issue quite a few times (I was reviewing the `diff`). Should "Repository" or "Quelle" be kept…? I've already discussed it some times ago and I think we kept "Quelle" everywhere. But yet again, I see repository (and hints like "Quelle (Repository)"). Not sure what I should do since I can't talk German.

**Comment by joergister** [comment]
I think everyone who uses this app, knows what a repository is. But even if he don't know, when he then turns to Github to submit his work, he will see himself in front of terms like repository. (Github is not available in German).
That's why I think, it would be OK to use "repository", instead of "Quelle". Especially since there is this hint " Quelle (Repository) ", which explains the meaning in that context. 
But its up to you ;)

**Comment by XyLoNaMiyX** [comment]
I'll just merge your work as is. It feels like a constant fight.

**Comment by XyLoNaMiyX** [comment]
Closed on [`67026bb`](https://github.com/LonamiWebs/Stringlate/commit/67026bb021a7dd4053be337581543f0c9b594788). Thanks!

**Comment by OffifialMITX** [comment]
As far as I can remember (and actually see) we kept Repository.

**Comment by XyLoNaMiyX** [comment]
Oops, forgot to close. And yes, I think we kept Repository? Anyway, either should be fine IMO.
