### ISSUE TITLE
String aliases should not be listed

### ISSUE THREAD

**Issue by gsantner** [LonamiWebs/Stringlate#95]
Version  0.9.9-fdroid:
Please don't list string aliases (`<string name="hi">@string/hello</string>`) per default. Usually they don't need to be /shouldn't be translated. Maybe an additional option could enable these, but pet default, these strings should not show up.

**Comment by Lonami** [comment]
Yes! I encountered this problem some time ago. But I don't really know how this could be solved. In some languages, it might need a totally different meaning, while in others, it might be OK for it to point to the right language. How should this be handled? Perhaps, "if string starts with `@`, then show a list to which string it should point to *or* allow entering a different text". But then, should the rest of strings also present this option (point to another existing string)?

**Comment by gsantner** [comment]
I would say its up to developers to decide whats an alias to another string. Users/Translators should not have to enter these. I dont expect from any translator to know every available key. 

Yep, hard without context.

I would suggest to hide such things per default (and to also not increases count ot translateable strings if one is detected).

I can think of an `Experts mode` option to show them.

**Comment by Lonami** [comment]
Sweet, I thought the references should also exist in the translated version*, but they don't need to - this simplifies things quite a bit. Done on commit [`2c75d45`](https://github.com/LonamiWebs/Stringlate/commit/2c75d454cee1c45b54dc45f31f83186d0b2e0a13) then :)

[*] See the following example:
- `values/strings.xml`:
```xml
<strings>
    <string name="example">An example</string>
    <string name="reference">@string/example</string>
</strings>
```

- `values-es/strings.xml`:
```xml
<strings>
    <string name="example">Un ejemplo</string>
</strings>
```

And you use `R.string.reference` on your code, it will also point to the right value in other languages.

**Comment by gsantner** [comment]
Yep, sorry, I missed to include this detail in the comment
