### ISSUE TITLE
translateable="false" gets ignored

### ISSUE THREAD

**Issue by gsantner** [LonamiWebs/Stringlate#96]
Version 0.9.9-fdroid:  
`translateable="false"` gets ignored - I tried every combination now and doesn't matter how, Stringlate always shows those strings as not translated, and requests to translate

Tried at <https://github.com/gsantner/memetastic/blob/master/app/src/main/res/values/arrays.xml>:
```
<string-array name="meme_categories" translateable="false">
        <item>@string/main__memecat__humans</item>
        <item>@string/main__memecat__animals</item>
        <item>@string/main__memecat__cartoon</item>
        <item>@string/main__memecat__rage</item>
</string-array>
```
```
<string-array name="meme_categories">
        <item translatable="false">@string/main__memecat__humans</item>
        <item translatable="false">@string/main__memecat__animals</item>
        <item translatable="false">@string/main__memecat__cartoon</item>
        <item translatable="false">@string/main__memecat__rage</item>
</string-array>
```
```
<string-array name="meme_categories" translateable="false">
        <item translatable="false">@string/main__memecat__humans</item>
        <item translatable="false">@string/main__memecat__animals</item>
        <item translatable="false">@string/main__memecat__cartoon</item>
        <item translatable="false">@string/main__memecat__rage</item>
</string-array>
```

![screenshot_20170404-200223](https://cloud.githubusercontent.com/assets/6735650/24671685/b47aaba6-1972-11e7-84fe-a07b3616f023.png)

**Comment by Lonami** [comment]
I'm not actually sure `translateable="false"` is a thing :)

Isn't it mispelled? Shouldn't it be `translatable="false"`? Let me try it out, to check whether Android Studio complains or not.

**Comment by gsantner** [comment]
Well, damn typos. Just did a quick try to get around the other issue posted some mins ago
